In [ ]:
#imports and environment
import csv
import json
import sys
import time

from collections import defaultdict
from datetime import datetime
from pathlib import Path

import torch #pytorch deep learning framework imports
import torch.nn.functional as torch_f

from PIL import Image
from torch.utils.data import Dataset, DataLoader

from transformers import ( 
    AutoImageProcessor,
    DetrForObjectDetection,
)

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Python: c:\Users\megdo\Desktop\underwater-object-detection\venv\Scripts\python.exe
PyTorch: 2.13.0+cpu
CUDA available: False

In [ ]:
#project and data paths
PROJECT_ROOT = Path(
    r"C:\Users\megdo\Desktop\underwater-object-detection"
)

ANNOTATION_DIR = ( # define the path for the annotation directory, which contains the COCO-style annotation files for the DUO dataset
    PROJECT_ROOT
    / "data"
    / "processed"
    / "DUO_coco"
    / "annotations"
)

TRAIN_IMAGE_DIR = ( # define the path for the training image directory, which contains the training images for the DUO dataset
    PROJECT_ROOT
    / "data"
    / "raw"
    / "DUO"
    / "images"
    / "train"
)

TEST_IMAGE_DIR = ( # define the path for the test image directory, which contains the test images for the DUO dataset
    PROJECT_ROOT
    / "data"
    / "raw"
    / "DUO"
    / "images"
    / "test"
)

TRAIN_JSON = ( 
    ANNOTATION_DIR
    / "instances_train_split.json"
)

VAL_JSON = (
    ANNOTATION_DIR
    / "instances_val_split.json"
)

TEST_JSON = (
    ANNOTATION_DIR
    / "instances_test_clean.json"
)

print("Project root:", PROJECT_ROOT.exists())
print("Training images:", TRAIN_IMAGE_DIR.exists())
print("Test images:", TEST_IMAGE_DIR.exists())
print("Training JSON:", TRAIN_JSON.exists())
print("Validation JSON:", VAL_JSON.exists())
print("Test JSON:", TEST_JSON.exists())

Project root: True
Training images: True
Test images: True
Training JSON: True
Validation JSON: True
Test JSON: True

In [ ]:
#labels and processor
MODEL_NAME = "facebook/detr-resnet-50"

id2label = { 
    0: "holothurian",
    1: "echinus",
    2: "scallop",
    3: "starfish",
}

label2id = {
    class_name: class_id
    for class_id, class_name in id2label.items()
}

processor = AutoImageProcessor.from_pretrained(
    MODEL_NAME
)

device = torch.device("cpu")

print("Processor loaded.")
print("Device:", device)
print("Classes:", id2label)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Processor loaded.
Device: cpu
Classes: {0: 'holothurian', 1: 'echinus', 2: 'scallop', 3: 'starfish'}

In [4]:
#model function
def create_fresh_detr_model():
    detr_model = (
        DetrForObjectDetection.from_pretrained(
            MODEL_NAME,
            num_labels=4,
            id2label=id2label,
            label2id=label2id,
            ignore_mismatched_sizes=True,
        )
    )

    return detr_model.to(device)

In [ ]:
#dataset class
class DUODetrDataset(Dataset):
    def __init__(
        self,
        image_dir,
        annotation_file,
        processor,
    ):
        self.image_dir = Path(image_dir)
        self.processor = processor

        with Path(annotation_file).open(
            "r",
            encoding="utf-8",
        ) as file:
            self.coco = json.load(file)

        self.images = self.coco["images"]

        self.annotations_by_image = defaultdict(list)

        for annotation in self.coco["annotations"]:
            self.annotations_by_image[
                annotation["image_id"]
            ].append(annotation)

        category_ids = sorted(
            category["id"]
            for category in self.coco["categories"]
        )

        # Convert DUO category IDs 1–4 to DETR labels 0–3
        self.category_to_label = {
            category_id: index
            for index, category_id in enumerate(
                category_ids
            )
        }

    def __len__(self):
        return len(self.images)

    def __getitem__(self, index):
        image_record = self.images[index]

        image_path = (
            self.image_dir
            / image_record["file_name"]
        )

        image = Image.open(
            image_path
        ).convert("RGB")

        annotations = []

        for annotation in self.annotations_by_image.get(
            image_record["id"],
            [],
        ):
            x, y, width, height = annotation["bbox"]

            if width <= 0 or height <= 0:
                continue

            annotations.append(
                {
                    "id": annotation["id"],
                    "image_id": image_record["id"],
                    "category_id":
                        self.category_to_label[
                            annotation["category_id"]
                        ],
                    "bbox": [
                        x,
                        y,
                        width,
                        height,
                    ],
                    "area": annotation.get(
                        "area",
                        width * height,
                    ),
                    "iscrowd": annotation.get(
                        "iscrowd",
                        0,
                    ),
                }
            )

        target = { 
            "image_id": image_record["id"],
            "annotations": annotations,
        }

        encoding = self.processor(
            images=image,
            annotations=target,
            return_tensors="pt",
            size={
                "shortest_edge": 416,
                "longest_edge": 416,
            },
        )

        pixel_values = encoding[
            "pixel_values"
        ].squeeze(0)

        labels = encoding["labels"][0]

        # These reshapes prevent the single-object error.
        labels["class_labels"] = labels[
            "class_labels"
        ].reshape(-1)

        labels["boxes"] = labels[
            "boxes"
        ].reshape(-1, 4)

        if "area" in labels:
            labels["area"] = labels[
                "area"
            ].reshape(-1)

        if "iscrowd" in labels:
            labels["iscrowd"] = labels[
                "iscrowd"
            ].reshape(-1)

        return {
            "pixel_values": pixel_values,
            "labels": labels,
        }

In [6]:
#creating dataset
train_dataset = DUODetrDataset(
    TRAIN_IMAGE_DIR,
    TRAIN_JSON,
    processor,
)

val_dataset = DUODetrDataset(
    TRAIN_IMAGE_DIR,
    VAL_JSON,
    processor,
)

test_dataset = DUODetrDataset(
    TEST_IMAGE_DIR,
    TEST_JSON,
    processor,
)

print("Training images:", len(train_dataset))
print("Validation images:", len(val_dataset))
print("Test images:", len(test_dataset))

Training images: 5336
Validation images: 1335
Test images: 1111

In [7]:
#manual padding function
def collate_fn(batch):
    pixel_values_list = [
        item["pixel_values"]
        for item in batch
    ]

    max_height = max(
        image.shape[1]
        for image in pixel_values_list
    )

    max_width = max(
        image.shape[2]
        for image in pixel_values_list
    )

    padded_images = []
    pixel_masks = []

    for image in pixel_values_list:
        _, height, width = image.shape

        pad_right = max_width - width
        pad_bottom = max_height - height

        padded_image = torch_f.pad(
            image,
            (
                0,
                pad_right,
                0,
                pad_bottom,
            ),
            value=0,
        )

        pixel_mask = torch.zeros(
            (max_height, max_width),
            dtype=torch.bool,
        )

        pixel_mask[:height, :width] = True

        padded_images.append(padded_image)
        pixel_masks.append(pixel_mask)

    return {
        "pixel_values": torch.stack(
            padded_images
        ),
        "pixel_mask": torch.stack(
            pixel_masks
        ),
        "labels": [
            item["labels"]
            for item in batch
        ],
    }

In [8]:
#data loaders
train_loader = DataLoader(
    train_dataset,
    batch_size=1,
    shuffle=True,
    num_workers=0,
    collate_fn=collate_fn,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=1,
    shuffle=False,
    num_workers=0,
    collate_fn=collate_fn,
)

test_loader = DataLoader(
    test_dataset,
    batch_size=1,
    shuffle=False,
    num_workers=0,
    collate_fn=collate_fn,
)

print("Training batches:", len(train_loader))
print("Validation batches:", len(val_loader))
print("Test batches:", len(test_loader))

Training batches: 5336
Validation batches: 1335
Test batches: 1111

In [9]:
#testing batch
batch = next(iter(train_loader))

print(
    "Pixel batch:",
    batch["pixel_values"].shape,
)

print(
    "Labels shape:",
    batch["labels"][0][
        "class_labels"
    ].shape,
)

print(
    "Boxes shape:",
    batch["labels"][0][
        "boxes"
    ].shape,
)

Pixel batch: torch.Size([1, 3, 234, 416])
Labels shape: torch.Size([9])
Boxes shape: torch.Size([9, 4])

In [10]:
#testing an image
single_object_index = None

for index, image_record in enumerate(
    train_dataset.images
):
    image_id = image_record["id"]

    annotation_count = len(
        train_dataset.annotations_by_image.get(
            image_id,
            [],
        )
    )

    if annotation_count == 1:
        single_object_index = index
        break

print(
    "Single-object image index:",
    single_object_index,
)

single_sample = train_dataset[
    single_object_index
]

print(
    "Single-image labels shape:",
    single_sample["labels"][
        "class_labels"
    ].shape,
)

print(
    "Single-image boxes shape:",
    single_sample["labels"][
        "boxes"
    ].shape,
)

Single-object image index: 30
Single-image labels shape: torch.Size([1])
Single-image boxes shape: torch.Size([1, 4])

In [11]:
#forward pass test
test_model = create_fresh_detr_model()
test_model.train()

test_batch = next(iter(train_loader))

pixel_values = test_batch[
    "pixel_values"
].to(device)

pixel_mask = test_batch[
    "pixel_mask"
].to(device)

labels = [
    {
        key: value.to(device)
        if isinstance(value, torch.Tensor)
        else value
        for key, value in target.items()
    }
    for target in test_batch["labels"]
]

with torch.no_grad():
    outputs = test_model(
        pixel_values=pixel_values,
        pixel_mask=pixel_mask,
        labels=labels,
    )

print(
    "Forward-pass loss:",
    float(outputs.loss),
)

for loss_name, loss_value in (
    outputs.loss_dict.items()
):
    print(
        loss_name,
        float(loss_value),
    )

[transformers] You passed `num_labels=4` which is incompatible to the `id2label` map of length `91`.
Loading weights: 100%|██████████| 530/530 [00:00<00:00, 5456.72it/s]
[transformers] DetrForObjectDetection LOAD REPORT from: facebook/detr-resnet-50
Key                                                            | Status     |
---------------------------------------------------------------+------------+----------------------------------------------------------------------------------------
model.backbone.model.layer4.0.downsample.1.num_batches_tracked | UNEXPECTED |
model.backbone.model.layer2.0.downsample.1.num_batches_tracked | UNEXPECTED |
model.backbone.model.layer1.0.downsample.1.num_batches_tracked | UNEXPECTED |
model.backbone.model.layer3.0.downsample.1.num_batches_tracked | UNEXPECTED |
class_labels_classifier.bias                                   | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([92]) vs model:torch.Size([5])
class_labels_classifier.weight                                 | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([92, 256]) vs model:torch.Size([5, 256])

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Forward-pass loss: 6.049570083618164
loss_ce 1.657971978187561
loss_bbox 0.43692636489868164
loss_giou 1.1034832000732422
cardinality_error 82.0

In [12]:
#deleting test model to free memory
del test_model
del outputs

model = create_fresh_detr_model()

print("Fresh full-training model created.")
print("Classes:", model.config.id2label)

[transformers] You passed `num_labels=4` which is incompatible to the `id2label` map of length `91`.
Loading weights: 100%|██████████| 530/530 [00:00<00:00, 8044.98it/s]
[transformers] DetrForObjectDetection LOAD REPORT from: facebook/detr-resnet-50
Key                                                            | Status     |
---------------------------------------------------------------+------------+----------------------------------------------------------------------------------------
model.backbone.model.layer4.0.downsample.1.num_batches_tracked | UNEXPECTED |
model.backbone.model.layer2.0.downsample.1.num_batches_tracked | UNEXPECTED |
model.backbone.model.layer1.0.downsample.1.num_batches_tracked | UNEXPECTED |
model.backbone.model.layer3.0.downsample.1.num_batches_tracked | UNEXPECTED |
class_labels_classifier.bias                                   | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([92]) vs model:torch.Size([5])
class_labels_classifier.weight                                 | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([92, 256]) vs model:torch.Size([5, 256])

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH:	ckpt weights were loaded, but they did not match the original empty weight shapes.

Fresh full-training model created.
Classes: {0: 'holothurian', 1: 'echinus', 2: 'scallop', 3: 'starfish'}

In [13]:
#optimiser and scheduler
backbone_parameters = []
other_parameters = []

for name, parameter in model.named_parameters():
    if not parameter.requires_grad:
        continue

    if "backbone" in name:
        backbone_parameters.append(parameter)
    else:
        other_parameters.append(parameter)

optimizer = torch.optim.AdamW(
    [
        {
            "params": other_parameters,
            "lr": 1e-4,
        },
        {
            "params": backbone_parameters,
            "lr": 1e-5,
        },
    ],
    weight_decay=1e-4,
)

scheduler = torch.optim.lr_scheduler.StepLR(
    optimizer,
    step_size=5,
    gamma=0.1,
)

print(
    "Main learning rate:",
    optimizer.param_groups[0]["lr"],
)

print(
    "Backbone learning rate:",
    optimizer.param_groups[1]["lr"],
)

Main learning rate: 0.0001
Backbone learning rate: 1e-05

In [14]:
#results folder
RUN_DIR = (
    PROJECT_ROOT
    / "results"
    / "detr"
    / "duo_detr_resnet50_baseline_corrected"
)

RUN_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

LATEST_CHECKPOINT = (
    RUN_DIR
    / "latest_checkpoint.pth"
)

BEST_CHECKPOINT = (
    RUN_DIR
    / "best_checkpoint.pth"
)

HISTORY_CSV = (
    RUN_DIR
    / "training_history.csv"
)

print("Run directory:", RUN_DIR)
print("Latest checkpoint:", LATEST_CHECKPOINT)
print("Best checkpoint:", BEST_CHECKPOINT)

Run directory: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Best checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\best_checkpoint.pth

In [15]:
#training function
def train_one_detr_epoch(
    model,
    data_loader,
    optimizer,
    device,
    epoch_number,
):
    model.train()

    epoch_start = time.perf_counter()
    total_epoch_loss = 0.0
    number_of_batches = len(data_loader)

    for batch_number, batch in enumerate(
        data_loader,
        start=1,
    ):
        pixel_values = batch[
            "pixel_values"
        ].to(device)

        pixel_mask = batch[
            "pixel_mask"
        ].to(device)

        labels = [
            {
                key: value.to(device)
                if isinstance(
                    value,
                    torch.Tensor,
                )
                else value
                for key, value in target.items()
            }
            for target in batch["labels"]
        ]

        outputs = model(
            pixel_values=pixel_values,
            pixel_mask=pixel_mask,
            labels=labels,
        )

        loss = outputs.loss

        if not torch.isfinite(loss):
            raise RuntimeError(
                f"Non-finite loss encountered: "
                f"{loss.item()}"
            )

        optimizer.zero_grad()
        loss.backward()

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=0.1,
        )

        optimizer.step()

        batch_loss = float(
            loss.detach()
        )

        total_epoch_loss += batch_loss

        if (
            batch_number == 1
            or batch_number % 100 == 0
        ):
            elapsed_hours = (
                time.perf_counter()
                - epoch_start
            ) / 3600

            average_so_far = (
                total_epoch_loss
                / batch_number
            )

            print(
                f"Epoch {epoch_number} | "
                f"Batch {batch_number}/"
                f"{number_of_batches} | "
                f"Loss: {batch_loss:.4f} | "
                f"Average: "
                f"{average_so_far:.4f} | "
                f"Elapsed: "
                f"{elapsed_hours:.2f} hours"
            )

    epoch_seconds = (
        time.perf_counter()
        - epoch_start
    )

    average_train_loss = (
        total_epoch_loss
        / number_of_batches
    )

    return (
        average_train_loss,
        epoch_seconds,
    )

In [16]:
#validation function
def calculate_detr_validation_loss(
    model,
    data_loader,
    device,
):
    model.eval()

    validation_start = time.perf_counter()
    total_validation_loss = 0.0
    number_of_batches = len(data_loader)

    with torch.no_grad():
        for batch_number, batch in enumerate(
            data_loader,
            start=1,
        ):
            pixel_values = batch[
                "pixel_values"
            ].to(device)

            pixel_mask = batch[
                "pixel_mask"
            ].to(device)

            labels = [
                {
                    key: value.to(device)
                    if isinstance(
                        value,
                        torch.Tensor,
                    )
                    else value
                    for key, value
                    in target.items()
                }
                for target in batch["labels"]
            ]

            outputs = model(
                pixel_values=pixel_values,
                pixel_mask=pixel_mask,
                labels=labels,
            )

            total_validation_loss += float(
                outputs.loss.detach()
            )

            if (
                batch_number == 1
                or batch_number % 100 == 0
            ):
                print(
                    f"Validation batch "
                    f"{batch_number}/"
                    f"{number_of_batches}"
                )

    average_validation_loss = (
        total_validation_loss
        / number_of_batches
    )

    validation_seconds = (
        time.perf_counter()
        - validation_start
    )

    return (
        average_validation_loss,
        validation_seconds,
    )

In [17]:
#history and checkpoint saving functions
def append_detr_history(
    epoch_number,
    average_train_loss,
    average_validation_loss,
    epoch_seconds,
    validation_seconds,
    main_learning_rate,
    backbone_learning_rate,
):
    file_exists = HISTORY_CSV.exists()

    with HISTORY_CSV.open(
        "a",
        newline="",
        encoding="utf-8",
    ) as file:
        writer = csv.writer(file)

        if not file_exists:
            writer.writerow(
                [
                    "epoch",
                    "average_train_loss",
                    "average_validation_loss",
                    "training_seconds",
                    "training_hours",
                    "validation_seconds",
                    "main_learning_rate",
                    "backbone_learning_rate",
                    "completion_time",
                ]
            )

        writer.writerow(
            [
                epoch_number,
                average_train_loss,
                average_validation_loss,
                epoch_seconds,
                epoch_seconds / 3600,
                validation_seconds,
                main_learning_rate,
                backbone_learning_rate,
                datetime.now().isoformat(
                    timespec="seconds"
                ),
            ]
        )


def save_detr_checkpoint(
    epoch_number,
    average_train_loss,
    average_validation_loss,
    cumulative_training_seconds,
    best_validation_loss,
    is_best,
):
    checkpoint = {
        "completed_epoch": epoch_number,
        "model_state_dict":
            model.state_dict(),
        "optimizer_state_dict":
            optimizer.state_dict(),
        "scheduler_state_dict":
            scheduler.state_dict(),
        "average_train_loss":
            average_train_loss,
        "average_validation_loss":
            average_validation_loss,
        "best_validation_loss":
            best_validation_loss,
        "cumulative_training_seconds":
            cumulative_training_seconds,
        "id2label": id2label,
    }

    torch.save(
        checkpoint,
        LATEST_CHECKPOINT,
    )

    epoch_checkpoint = (
        RUN_DIR
        / f"checkpoint_epoch_"
          f"{epoch_number:02d}.pth"
    )

    torch.save(
        checkpoint,
        epoch_checkpoint,
    )

    if is_best:
        torch.save(
            checkpoint,
            BEST_CHECKPOINT,
        )

        print(
            "New best validation checkpoint saved."
        )

    print(
        "Latest checkpoint:",
        LATEST_CHECKPOINT,
    )

    print(
        "Epoch checkpoint:",
        epoch_checkpoint,
    )

In [18]:
#function to run and save epoch 1
def run_and_save_detr_epoch(
    epoch_number,
    cumulative_training_seconds,
    best_validation_loss,
):
    main_learning_rate = (
        optimizer.param_groups[0]["lr"]
    )

    backbone_learning_rate = (
        optimizer.param_groups[1]["lr"]
    )

    print("Beginning full DETR training")
    print("Epoch:", epoch_number)
    print(
        "Training images:",
        len(train_dataset),
    )
    print(
        "Main learning rate:",
        main_learning_rate,
    )
    print(
        "Backbone learning rate:",
        backbone_learning_rate,
    )
    print("Start time:", datetime.now())

    average_train_loss, epoch_seconds = (
        train_one_detr_epoch(
            model=model,
            data_loader=train_loader,
            optimizer=optimizer,
            device=device,
            epoch_number=epoch_number,
        )
    )

    average_validation_loss, validation_seconds = (
        calculate_detr_validation_loss(
            model=model,
            data_loader=val_loader,
            device=device,
        )
    )

    cumulative_training_seconds += (
        epoch_seconds
    )

    is_best = (
        average_validation_loss
        < best_validation_loss
    )

    if is_best:
        best_validation_loss = (
            average_validation_loss
        )

    scheduler.step()

    append_detr_history(
        epoch_number=epoch_number,
        average_train_loss=
            average_train_loss,
        average_validation_loss=
            average_validation_loss,
        epoch_seconds=epoch_seconds,
        validation_seconds=
            validation_seconds,
        main_learning_rate=
            main_learning_rate,
        backbone_learning_rate=
            backbone_learning_rate,
    )

    save_detr_checkpoint(
        epoch_number=epoch_number,
        average_train_loss=
            average_train_loss,
        average_validation_loss=
            average_validation_loss,
        cumulative_training_seconds=
            cumulative_training_seconds,
        best_validation_loss=
            best_validation_loss,
        is_best=is_best,
    )

    print("\nEpoch completed successfully.")
    print(
        f"Training loss: "
        f"{average_train_loss:.4f}"
    )
    print(
        f"Validation loss: "
        f"{average_validation_loss:.4f}"
    )
    print(
        f"Training time: "
        f"{epoch_seconds / 3600:.2f} hours"
    )
    print(
        f"Validation time: "
        f"{validation_seconds / 3600:.2f} hours"
    )
    print(
        "Cumulative training time:",
        f"{cumulative_training_seconds / 3600:.2f} hours",
    )
    print("Finish time:", datetime.now())

    return (
        cumulative_training_seconds,
        best_validation_loss,
    )

In [19]:
#start epoch 1
epoch_number = 1
cumulative_training_seconds = 0.0
best_validation_loss = float("inf")

(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 1
Training images: 5336
Main learning rate: 0.0001
Backbone learning rate: 1e-05
Start time: 2026-07-22 12:09:17.660432
Epoch 1 | Batch 1/5336 | Loss: 10.4199 | Average: 10.4199 | Elapsed: 0.00 hours
Epoch 1 | Batch 100/5336 | Loss: 3.5155 | Average: 3.4317 | Elapsed: 0.02 hours
Epoch 1 | Batch 200/5336 | Loss: 2.3880 | Average: 3.1962 | Elapsed: 0.04 hours
Epoch 1 | Batch 300/5336 | Loss: 2.3089 | Average: 3.0826 | Elapsed: 0.06 hours
Epoch 1 | Batch 400/5336 | Loss: 2.1083 | Average: 3.0410 | Elapsed: 0.08 hours
Epoch 1 | Batch 500/5336 | Loss: 3.1797 | Average: 3.0326 | Elapsed: 0.10 hours
Epoch 1 | Batch 600/5336 | Loss: 3.5371 | Average: 2.9862 | Elapsed: 0.12 hours
Epoch 1 | Batch 700/5336 | Loss: 4.2355 | Average: 2.9475 | Elapsed: 0.14 hours
Epoch 1 | Batch 800/5336 | Loss: 2.4580 | Average: 2.9347 | Elapsed: 0.16 hours
Epoch 1 | Batch 900/5336 | Loss: 2.5950 | Average: 2.8798 | Elapsed: 0.18 hours
Epoch 1 | Batch 1000/5336 | Loss: 4.4715 | Average: 2.8674 | Elapsed: 0.20 hours
Epoch 1 | Batch 1100/5336 | Loss: 1.9953 | Average: 2.8483 | Elapsed: 0.22 hours
Epoch 1 | Batch 1200/5336 | Loss: 2.2429 | Average: 2.8302 | Elapsed: 0.24 hours
Epoch 1 | Batch 1300/5336 | Loss: 3.4467 | Average: 2.8241 | Elapsed: 0.26 hours
Epoch 1 | Batch 1400/5336 | Loss: 3.0049 | Average: 2.8251 | Elapsed: 0.28 hours
Epoch 1 | Batch 1500/5336 | Loss: 2.1687 | Average: 2.8165 | Elapsed: 0.30 hours
Epoch 1 | Batch 1600/5336 | Loss: 2.5751 | Average: 2.8250 | Elapsed: 0.32 hours
Epoch 1 | Batch 1700/5336 | Loss: 3.2992 | Average: 2.8152 | Elapsed: 0.33 hours
Epoch 1 | Batch 1800/5336 | Loss: 3.2582 | Average: 2.8169 | Elapsed: 0.35 hours
Epoch 1 | Batch 1900/5336 | Loss: 2.1435 | Average: 2.7999 | Elapsed: 0.37 hours
Epoch 1 | Batch 2000/5336 | Loss: 3.4436 | Average: 2.7923 | Elapsed: 0.39 hours
Epoch 1 | Batch 2100/5336 | Loss: 2.1374 | Average: 2.7723 | Elapsed: 0.41 hours
Epoch 1 | Batch 2200/5336 | Loss: 3.7630 | Average: 2.7796 | Elapsed: 0.43 hours
Epoch 1 | Batch 2300/5336 | Loss: 2.8450 | Average: 2.7847 | Elapsed: 0.45 hours
Epoch 1 | Batch 2400/5336 | Loss: 3.4968 | Average: 2.7825 | Elapsed: 0.47 hours
Epoch 1 | Batch 2500/5336 | Loss: 3.8838 | Average: 2.7781 | Elapsed: 0.49 hours
Epoch 1 | Batch 2600/5336 | Loss: 1.9862 | Average: 2.7686 | Elapsed: 0.51 hours
Epoch 1 | Batch 2700/5336 | Loss: 3.1177 | Average: 2.7653 | Elapsed: 0.53 hours
Epoch 1 | Batch 2800/5336 | Loss: 2.5166 | Average: 2.7570 | Elapsed: 0.54 hours
Epoch 1 | Batch 2900/5336 | Loss: 3.2859 | Average: 2.7529 | Elapsed: 0.56 hours
Epoch 1 | Batch 3000/5336 | Loss: 2.4972 | Average: 2.7489 | Elapsed: 0.58 hours
Epoch 1 | Batch 3100/5336 | Loss: 3.6319 | Average: 2.7403 | Elapsed: 0.60 hours
Epoch 1 | Batch 3200/5336 | Loss: 2.4082 | Average: 2.7370 | Elapsed: 0.62 hours
Epoch 1 | Batch 3300/5336 | Loss: 2.5164 | Average: 2.7312 | Elapsed: 0.64 hours
Epoch 1 | Batch 3400/5336 | Loss: 3.9010 | Average: 2.7286 | Elapsed: 0.66 hours
Epoch 1 | Batch 3500/5336 | Loss: 2.9677 | Average: 2.7349 | Elapsed: 0.68 hours
Epoch 1 | Batch 3600/5336 | Loss: 2.3438 | Average: 2.7263 | Elapsed: 0.70 hours
Epoch 1 | Batch 3700/5336 | Loss: 3.3418 | Average: 2.7215 | Elapsed: 0.72 hours
Epoch 1 | Batch 3800/5336 | Loss: 1.2399 | Average: 2.7173 | Elapsed: 0.73 hours
Epoch 1 | Batch 3900/5336 | Loss: 2.2662 | Average: 2.7187 | Elapsed: 0.75 hours
Epoch 1 | Batch 4000/5336 | Loss: 2.7900 | Average: 2.7195 | Elapsed: 0.77 hours
Epoch 1 | Batch 4100/5336 | Loss: 2.8731 | Average: 2.7153 | Elapsed: 0.79 hours
Epoch 1 | Batch 4200/5336 | Loss: 2.7090 | Average: 2.7126 | Elapsed: 0.81 hours
Epoch 1 | Batch 4300/5336 | Loss: 3.8806 | Average: 2.7093 | Elapsed: 0.83 hours
Epoch 1 | Batch 4400/5336 | Loss: 1.8532 | Average: 2.7056 | Elapsed: 0.85 hours
Epoch 1 | Batch 4500/5336 | Loss: 2.7497 | Average: 2.7040 | Elapsed: 0.87 hours
Epoch 1 | Batch 4600/5336 | Loss: 1.7678 | Average: 2.7021 | Elapsed: 0.89 hours
Epoch 1 | Batch 4700/5336 | Loss: 3.2408 | Average: 2.7000 | Elapsed: 0.91 hours
Epoch 1 | Batch 4800/5336 | Loss: 1.9048 | Average: 2.6976 | Elapsed: 0.93 hours
Epoch 1 | Batch 4900/5336 | Loss: 2.7729 | Average: 2.6952 | Elapsed: 0.95 hours
Epoch 1 | Batch 5000/5336 | Loss: 3.1803 | Average: 2.6885 | Elapsed: 0.97 hours
Epoch 1 | Batch 5100/5336 | Loss: 3.0551 | Average: 2.6810 | Elapsed: 0.99 hours
Epoch 1 | Batch 5200/5336 | Loss: 1.9032 | Average: 2.6737 | Elapsed: 1.01 hours
Epoch 1 | Batch 5300/5336 | Loss: 4.6668 | Average: 2.6702 | Elapsed: 1.03 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_01.pth

Epoch completed successfully.
Training loss: 2.6699
Validation loss: 2.3566
Training time: 1.03 hours
Validation time: 0.07 hours
Cumulative training time: 1.03 hours
Finish time: 2026-07-22 13:15:31.045212

In [20]:
#epcoh 1 checkpoint
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print(
    "Cumulative training time:",
    f"{cumulative_training_seconds / 3600:.2f} hours",
)
print(
    "Best validation loss:",
    best_validation_loss,
)
print(
    "Current main learning rate:",
    optimizer.param_groups[0]["lr"],
)

Completed epoch: 1
Next epoch: 2
Cumulative training time: 1.03 hours
Best validation loss: 2.356624818372816
Current main learning rate: 0.0001

In [21]:
#run epoch 2
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 2
Training images: 5336
Main learning rate: 0.0001
Backbone learning rate: 1e-05
Start time: 2026-07-22 13:45:58.302490
Epoch 2 | Batch 1/5336 | Loss: 1.8504 | Average: 1.8504 | Elapsed: 0.00 hours
Epoch 2 | Batch 100/5336 | Loss: 1.8357 | Average: 2.4874 | Elapsed: 0.03 hours
Epoch 2 | Batch 200/5336 | Loss: 2.8583 | Average: 2.4280 | Elapsed: 0.06 hours
Epoch 2 | Batch 300/5336 | Loss: 2.1305 | Average: 2.3986 | Elapsed: 0.09 hours
Epoch 2 | Batch 400/5336 | Loss: 2.8391 | Average: 2.3590 | Elapsed: 0.28 hours
Epoch 2 | Batch 500/5336 | Loss: 1.1373 | Average: 2.3803 | Elapsed: 0.34 hours
Epoch 2 | Batch 600/5336 | Loss: 3.6678 | Average: 2.3661 | Elapsed: 0.39 hours
Epoch 2 | Batch 700/5336 | Loss: 2.5214 | Average: 2.3461 | Elapsed: 0.42 hours
Epoch 2 | Batch 800/5336 | Loss: 4.9134 | Average: 2.3337 | Elapsed: 0.47 hours
Epoch 2 | Batch 900/5336 | Loss: 2.8176 | Average: 2.3328 | Elapsed: 0.53 hours
Epoch 2 | Batch 1000/5336 | Loss: 2.2768 | Average: 2.3428 | Elapsed: 0.59 hours
Epoch 2 | Batch 1100/5336 | Loss: 2.6210 | Average: 2.3525 | Elapsed: 0.78 hours
Epoch 2 | Batch 1200/5336 | Loss: 2.0971 | Average: 2.3471 | Elapsed: 0.84 hours
Epoch 2 | Batch 1300/5336 | Loss: 4.6747 | Average: 2.3390 | Elapsed: 0.89 hours
Epoch 2 | Batch 1400/5336 | Loss: 2.1900 | Average: 2.3347 | Elapsed: 0.95 hours
Epoch 2 | Batch 1500/5336 | Loss: 2.5095 | Average: 2.3180 | Elapsed: 1.01 hours
Epoch 2 | Batch 1600/5336 | Loss: 2.1350 | Average: 2.3042 | Elapsed: 1.07 hours
Epoch 2 | Batch 1700/5336 | Loss: 2.4028 | Average: 2.2965 | Elapsed: 1.12 hours
Epoch 2 | Batch 1800/5336 | Loss: 1.8887 | Average: 2.2879 | Elapsed: 1.17 hours
Epoch 2 | Batch 1900/5336 | Loss: 1.8597 | Average: 2.2806 | Elapsed: 1.23 hours
Epoch 2 | Batch 2000/5336 | Loss: 2.2390 | Average: 2.2684 | Elapsed: 1.28 hours
Epoch 2 | Batch 2100/5336 | Loss: 2.1451 | Average: 2.2627 | Elapsed: 1.34 hours
Epoch 2 | Batch 2200/5336 | Loss: 2.0808 | Average: 2.2549 | Elapsed: 1.39 hours
Epoch 2 | Batch 2300/5336 | Loss: 2.5482 | Average: 2.2569 | Elapsed: 1.45 hours
Epoch 2 | Batch 2400/5336 | Loss: 1.7825 | Average: 2.2495 | Elapsed: 1.50 hours
Epoch 2 | Batch 2500/5336 | Loss: 2.8203 | Average: 2.2429 | Elapsed: 1.54 hours
Epoch 2 | Batch 2600/5336 | Loss: 1.7504 | Average: 2.2467 | Elapsed: 1.59 hours
Epoch 2 | Batch 2700/5336 | Loss: 2.4633 | Average: 2.2451 | Elapsed: 1.64 hours
Epoch 2 | Batch 2800/5336 | Loss: 1.6816 | Average: 2.2451 | Elapsed: 1.69 hours
Epoch 2 | Batch 2900/5336 | Loss: 2.3375 | Average: 2.2397 | Elapsed: 1.74 hours
Epoch 2 | Batch 3000/5336 | Loss: 1.9023 | Average: 2.2355 | Elapsed: 1.79 hours
Epoch 2 | Batch 3100/5336 | Loss: 4.2111 | Average: 2.2335 | Elapsed: 1.83 hours
Epoch 2 | Batch 3200/5336 | Loss: 2.1984 | Average: 2.2288 | Elapsed: 1.88 hours
Epoch 2 | Batch 3300/5336 | Loss: 1.6701 | Average: 2.2244 | Elapsed: 1.92 hours
Epoch 2 | Batch 3400/5336 | Loss: 2.6555 | Average: 2.2207 | Elapsed: 1.97 hours
Epoch 2 | Batch 3500/5336 | Loss: 1.8487 | Average: 2.2136 | Elapsed: 2.02 hours
Epoch 2 | Batch 3600/5336 | Loss: 3.6605 | Average: 2.2098 | Elapsed: 2.05 hours
Epoch 2 | Batch 3700/5336 | Loss: 0.6488 | Average: 2.2040 | Elapsed: 2.08 hours
Epoch 2 | Batch 3800/5336 | Loss: 1.5862 | Average: 2.2019 | Elapsed: 2.12 hours
Epoch 2 | Batch 3900/5336 | Loss: 2.0538 | Average: 2.1976 | Elapsed: 2.14 hours
Epoch 2 | Batch 4000/5336 | Loss: 2.3071 | Average: 2.1941 | Elapsed: 2.16 hours
Epoch 2 | Batch 4100/5336 | Loss: 2.3374 | Average: 2.1885 | Elapsed: 2.18 hours
Epoch 2 | Batch 4200/5336 | Loss: 1.7258 | Average: 2.1831 | Elapsed: 2.20 hours
Epoch 2 | Batch 4300/5336 | Loss: 1.3766 | Average: 2.1798 | Elapsed: 2.23 hours
Epoch 2 | Batch 4400/5336 | Loss: 1.4083 | Average: 2.1774 | Elapsed: 2.25 hours
Epoch 2 | Batch 4500/5336 | Loss: 2.7507 | Average: 2.1693 | Elapsed: 2.27 hours
Epoch 2 | Batch 4600/5336 | Loss: 1.8971 | Average: 2.1666 | Elapsed: 2.29 hours
Epoch 2 | Batch 4700/5336 | Loss: 1.4614 | Average: 2.1648 | Elapsed: 2.31 hours
Epoch 2 | Batch 4800/5336 | Loss: 2.7801 | Average: 2.1615 | Elapsed: 2.33 hours
Epoch 2 | Batch 4900/5336 | Loss: 1.8424 | Average: 2.1604 | Elapsed: 2.35 hours
Epoch 2 | Batch 5000/5336 | Loss: 1.9715 | Average: 2.1557 | Elapsed: 2.37 hours
Epoch 2 | Batch 5100/5336 | Loss: 2.5816 | Average: 2.1516 | Elapsed: 2.39 hours
Epoch 2 | Batch 5200/5336 | Loss: 2.0202 | Average: 2.1474 | Elapsed: 2.41 hours
Epoch 2 | Batch 5300/5336 | Loss: 1.7859 | Average: 2.1423 | Elapsed: 2.43 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_02.pth

Epoch completed successfully.
Training loss: 2.1422
Validation loss: 1.8882
Training time: 2.44 hours
Validation time: 0.07 hours
Cumulative training time: 3.47 hours
Finish time: 2026-07-22 16:16:39.521057

In [22]:
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print(
    "Best validation loss:",
    best_validation_loss,
)

Completed epoch: 2
Next epoch: 3
Best validation loss: 1.8882443545211791

In [23]:
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 3
Training images: 5336
Main learning rate: 0.0001
Backbone learning rate: 1e-05
Start time: 2026-07-22 16:35:16.181905
Epoch 3 | Batch 1/5336 | Loss: 2.7265 | Average: 2.7265 | Elapsed: 0.00 hours
Epoch 3 | Batch 100/5336 | Loss: 1.7876 | Average: 1.8228 | Elapsed: 0.02 hours
Epoch 3 | Batch 200/5336 | Loss: 1.9521 | Average: 1.8974 | Elapsed: 0.04 hours
Epoch 3 | Batch 300/5336 | Loss: 2.1659 | Average: 1.9126 | Elapsed: 0.06 hours
Epoch 3 | Batch 400/5336 | Loss: 1.6199 | Average: 1.9125 | Elapsed: 0.08 hours
Epoch 3 | Batch 500/5336 | Loss: 2.1522 | Average: 1.9083 | Elapsed: 0.10 hours
Epoch 3 | Batch 600/5336 | Loss: 1.7431 | Average: 1.9084 | Elapsed: 0.12 hours
Epoch 3 | Batch 700/5336 | Loss: 2.0608 | Average: 1.9192 | Elapsed: 0.14 hours
Epoch 3 | Batch 800/5336 | Loss: 1.5608 | Average: 1.9206 | Elapsed: 0.16 hours
Epoch 3 | Batch 900/5336 | Loss: 0.6836 | Average: 1.9101 | Elapsed: 0.19 hours
Epoch 3 | Batch 1000/5336 | Loss: 1.6990 | Average: 1.9082 | Elapsed: 0.21 hours
Epoch 3 | Batch 1100/5336 | Loss: 1.7940 | Average: 1.9069 | Elapsed: 0.23 hours
Epoch 3 | Batch 1200/5336 | Loss: 1.6212 | Average: 1.8999 | Elapsed: 0.25 hours
Epoch 3 | Batch 1300/5336 | Loss: 1.3648 | Average: 1.9052 | Elapsed: 0.27 hours
Epoch 3 | Batch 1400/5336 | Loss: 1.2717 | Average: 1.9097 | Elapsed: 0.29 hours
Epoch 3 | Batch 1500/5336 | Loss: 2.2683 | Average: 1.9054 | Elapsed: 0.31 hours
Epoch 3 | Batch 1600/5336 | Loss: 1.5860 | Average: 1.9191 | Elapsed: 0.33 hours
Epoch 3 | Batch 1700/5336 | Loss: 1.6622 | Average: 1.9200 | Elapsed: 0.35 hours
Epoch 3 | Batch 1800/5336 | Loss: 1.2369 | Average: 1.9109 | Elapsed: 0.37 hours
Epoch 3 | Batch 1900/5336 | Loss: 2.0885 | Average: 1.9094 | Elapsed: 0.39 hours
Epoch 3 | Batch 2000/5336 | Loss: 3.0865 | Average: 1.9092 | Elapsed: 0.41 hours
Epoch 3 | Batch 2100/5336 | Loss: 1.5701 | Average: 1.9153 | Elapsed: 0.43 hours
Epoch 3 | Batch 2200/5336 | Loss: 1.7555 | Average: 1.9104 | Elapsed: 0.45 hours
Epoch 3 | Batch 2300/5336 | Loss: 3.0722 | Average: 1.9112 | Elapsed: 0.47 hours
Epoch 3 | Batch 2400/5336 | Loss: 1.8980 | Average: 1.9075 | Elapsed: 0.49 hours
Epoch 3 | Batch 2500/5336 | Loss: 2.0558 | Average: 1.9061 | Elapsed: 0.51 hours
Epoch 3 | Batch 2600/5336 | Loss: 0.0789 | Average: 1.9028 | Elapsed: 0.53 hours
Epoch 3 | Batch 2700/5336 | Loss: 1.4585 | Average: 1.8996 | Elapsed: 0.55 hours
Epoch 3 | Batch 2800/5336 | Loss: 1.8796 | Average: 1.8990 | Elapsed: 0.57 hours
Epoch 3 | Batch 2900/5336 | Loss: 2.4679 | Average: 1.8955 | Elapsed: 0.59 hours
Epoch 3 | Batch 3000/5336 | Loss: 1.9324 | Average: 1.9009 | Elapsed: 0.62 hours
Epoch 3 | Batch 3100/5336 | Loss: 1.5405 | Average: 1.8989 | Elapsed: 0.64 hours
Epoch 3 | Batch 3200/5336 | Loss: 2.3957 | Average: 1.8997 | Elapsed: 0.66 hours
Epoch 3 | Batch 3300/5336 | Loss: 0.9723 | Average: 1.8987 | Elapsed: 0.68 hours
Epoch 3 | Batch 3400/5336 | Loss: 1.4598 | Average: 1.9005 | Elapsed: 0.70 hours
Epoch 3 | Batch 3500/5336 | Loss: 1.8153 | Average: 1.8998 | Elapsed: 0.72 hours
Epoch 3 | Batch 3600/5336 | Loss: 1.6530 | Average: 1.8992 | Elapsed: 0.74 hours
Epoch 3 | Batch 3700/5336 | Loss: 2.8032 | Average: 1.8984 | Elapsed: 0.76 hours
Epoch 3 | Batch 3800/5336 | Loss: 1.2401 | Average: 1.8970 | Elapsed: 0.78 hours
Epoch 3 | Batch 3900/5336 | Loss: 1.0656 | Average: 1.8962 | Elapsed: 0.80 hours
Epoch 3 | Batch 4000/5336 | Loss: 2.0815 | Average: 1.8925 | Elapsed: 0.82 hours
Epoch 3 | Batch 4100/5336 | Loss: 1.3868 | Average: 1.8909 | Elapsed: 0.84 hours
Epoch 3 | Batch 4200/5336 | Loss: 1.4753 | Average: 1.8911 | Elapsed: 0.86 hours
Epoch 3 | Batch 4300/5336 | Loss: 2.7141 | Average: 1.8875 | Elapsed: 0.88 hours
Epoch 3 | Batch 4400/5336 | Loss: 1.2823 | Average: 1.8839 | Elapsed: 0.90 hours
Epoch 3 | Batch 4500/5336 | Loss: 2.4221 | Average: 1.8846 | Elapsed: 0.92 hours
Epoch 3 | Batch 4600/5336 | Loss: 1.9706 | Average: 1.8841 | Elapsed: 0.94 hours
Epoch 3 | Batch 4700/5336 | Loss: 3.1149 | Average: 1.8832 | Elapsed: 0.96 hours
Epoch 3 | Batch 4800/5336 | Loss: 2.3164 | Average: 1.8847 | Elapsed: 0.98 hours
Epoch 3 | Batch 4900/5336 | Loss: 2.3589 | Average: 1.8828 | Elapsed: 1.00 hours
Epoch 3 | Batch 5000/5336 | Loss: 1.5689 | Average: 1.8832 | Elapsed: 1.03 hours
Epoch 3 | Batch 5100/5336 | Loss: 2.0151 | Average: 1.8810 | Elapsed: 1.05 hours
Epoch 3 | Batch 5200/5336 | Loss: 2.9924 | Average: 1.8821 | Elapsed: 1.07 hours
Epoch 3 | Batch 5300/5336 | Loss: 2.1129 | Average: 1.8818 | Elapsed: 1.09 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_03.pth

Epoch completed successfully.
Training loss: 1.8804
Validation loss: 1.6978
Training time: 1.09 hours
Validation time: 0.09 hours
Cumulative training time: 4.57 hours
Finish time: 2026-07-22 17:46:39.617763

In [24]:
#checkpoint after epoch 3
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print(
    "Best validation loss:",
    best_validation_loss,
)

Completed epoch: 3
Next epoch: 4
Best validation loss: 1.697843568013067

In [25]:
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 4
Training images: 5336
Main learning rate: 0.0001
Backbone learning rate: 1e-05
Start time: 2026-07-22 17:51:35.953846
Epoch 4 | Batch 1/5336 | Loss: 2.5143 | Average: 2.5143 | Elapsed: 0.00 hours
Epoch 4 | Batch 100/5336 | Loss: 1.1835 | Average: 1.7998 | Elapsed: 0.02 hours
Epoch 4 | Batch 200/5336 | Loss: 1.7139 | Average: 1.7286 | Elapsed: 0.04 hours
Epoch 4 | Batch 300/5336 | Loss: 2.0769 | Average: 1.7110 | Elapsed: 0.06 hours
Epoch 4 | Batch 400/5336 | Loss: 1.6328 | Average: 1.7068 | Elapsed: 0.08 hours
Epoch 4 | Batch 500/5336 | Loss: 1.7795 | Average: 1.7211 | Elapsed: 0.10 hours
Epoch 4 | Batch 600/5336 | Loss: 1.2618 | Average: 1.7328 | Elapsed: 0.12 hours
Epoch 4 | Batch 700/5336 | Loss: 2.6413 | Average: 1.7320 | Elapsed: 0.14 hours
Epoch 4 | Batch 800/5336 | Loss: 1.0082 | Average: 1.7299 | Elapsed: 0.17 hours
Epoch 4 | Batch 900/5336 | Loss: 2.1939 | Average: 1.7274 | Elapsed: 0.19 hours
Epoch 4 | Batch 1000/5336 | Loss: 1.0412 | Average: 1.7277 | Elapsed: 0.21 hours
Epoch 4 | Batch 1100/5336 | Loss: 1.8490 | Average: 1.7341 | Elapsed: 0.23 hours
Epoch 4 | Batch 1200/5336 | Loss: 2.5626 | Average: 1.7421 | Elapsed: 0.25 hours
Epoch 4 | Batch 1300/5336 | Loss: 2.0773 | Average: 1.7411 | Elapsed: 0.27 hours
Epoch 4 | Batch 1400/5336 | Loss: 1.5552 | Average: 1.7460 | Elapsed: 0.29 hours
Epoch 4 | Batch 1500/5336 | Loss: 1.6404 | Average: 1.7438 | Elapsed: 0.31 hours
Epoch 4 | Batch 1600/5336 | Loss: 1.3239 | Average: 1.7441 | Elapsed: 0.33 hours
Epoch 4 | Batch 1700/5336 | Loss: 1.6394 | Average: 1.7432 | Elapsed: 0.35 hours
Epoch 4 | Batch 1800/5336 | Loss: 2.4124 | Average: 1.7390 | Elapsed: 0.37 hours
Epoch 4 | Batch 1900/5336 | Loss: 1.4076 | Average: 1.7423 | Elapsed: 0.39 hours
Epoch 4 | Batch 2000/5336 | Loss: 2.7498 | Average: 1.7416 | Elapsed: 0.41 hours
Epoch 4 | Batch 2100/5336 | Loss: 1.3181 | Average: 1.7488 | Elapsed: 0.43 hours
Epoch 4 | Batch 2200/5336 | Loss: 1.8582 | Average: 1.7529 | Elapsed: 0.45 hours
Epoch 4 | Batch 2300/5336 | Loss: 2.1811 | Average: 1.7614 | Elapsed: 0.48 hours
Epoch 4 | Batch 2400/5336 | Loss: 2.0668 | Average: 1.7603 | Elapsed: 0.50 hours
Epoch 4 | Batch 2500/5336 | Loss: 2.4807 | Average: 1.7592 | Elapsed: 0.52 hours
Epoch 4 | Batch 2600/5336 | Loss: 0.9573 | Average: 1.7581 | Elapsed: 0.54 hours
Epoch 4 | Batch 2700/5336 | Loss: 1.3476 | Average: 1.7565 | Elapsed: 0.56 hours
Epoch 4 | Batch 2800/5336 | Loss: 1.3713 | Average: 1.7528 | Elapsed: 0.58 hours
Epoch 4 | Batch 2900/5336 | Loss: 0.8623 | Average: 1.7488 | Elapsed: 0.60 hours
Epoch 4 | Batch 3000/5336 | Loss: 1.7643 | Average: 1.7488 | Elapsed: 0.62 hours
Epoch 4 | Batch 3100/5336 | Loss: 0.8555 | Average: 1.7473 | Elapsed: 0.64 hours
Epoch 4 | Batch 3200/5336 | Loss: 1.3734 | Average: 1.7508 | Elapsed: 0.66 hours
Epoch 4 | Batch 3300/5336 | Loss: 2.0392 | Average: 1.7543 | Elapsed: 0.68 hours
Epoch 4 | Batch 3400/5336 | Loss: 0.1400 | Average: 1.7546 | Elapsed: 0.71 hours
Epoch 4 | Batch 3500/5336 | Loss: 1.4921 | Average: 1.7532 | Elapsed: 0.73 hours
Epoch 4 | Batch 3600/5336 | Loss: 1.0254 | Average: 1.7536 | Elapsed: 0.75 hours
Epoch 4 | Batch 3700/5336 | Loss: 1.6573 | Average: 1.7542 | Elapsed: 0.77 hours
Epoch 4 | Batch 3800/5336 | Loss: 1.9515 | Average: 1.7553 | Elapsed: 0.79 hours
Epoch 4 | Batch 3900/5336 | Loss: 1.2355 | Average: 1.7534 | Elapsed: 0.81 hours
Epoch 4 | Batch 4000/5336 | Loss: 1.7467 | Average: 1.7513 | Elapsed: 0.83 hours
Epoch 4 | Batch 4100/5336 | Loss: 3.1144 | Average: 1.7501 | Elapsed: 0.85 hours
Epoch 4 | Batch 4200/5336 | Loss: 2.8465 | Average: 1.7520 | Elapsed: 0.87 hours
Epoch 4 | Batch 4300/5336 | Loss: 2.2836 | Average: 1.7532 | Elapsed: 0.89 hours
Epoch 4 | Batch 4400/5336 | Loss: 1.1798 | Average: 1.7511 | Elapsed: 0.92 hours
Epoch 4 | Batch 4500/5336 | Loss: 2.1086 | Average: 1.7503 | Elapsed: 0.94 hours
Epoch 4 | Batch 4600/5336 | Loss: 1.8264 | Average: 1.7466 | Elapsed: 0.96 hours
Epoch 4 | Batch 4700/5336 | Loss: 1.4324 | Average: 1.7444 | Elapsed: 0.98 hours
Epoch 4 | Batch 4800/5336 | Loss: 0.6062 | Average: 1.7408 | Elapsed: 1.00 hours
Epoch 4 | Batch 4900/5336 | Loss: 1.0300 | Average: 1.7381 | Elapsed: 1.02 hours
Epoch 4 | Batch 5000/5336 | Loss: 1.1104 | Average: 1.7370 | Elapsed: 1.04 hours
Epoch 4 | Batch 5100/5336 | Loss: 2.2606 | Average: 1.7398 | Elapsed: 1.06 hours
Epoch 4 | Batch 5200/5336 | Loss: 1.8618 | Average: 1.7389 | Elapsed: 1.08 hours
Epoch 4 | Batch 5300/5336 | Loss: 1.6461 | Average: 1.7392 | Elapsed: 1.10 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_04.pth

Epoch completed successfully.
Training loss: 1.7401
Validation loss: 1.7550
Training time: 1.11 hours
Validation time: 0.08 hours
Cumulative training time: 5.68 hours
Finish time: 2026-07-22 19:02:48.533654

In [26]:
#loading checkpoint after epoch 4
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print("Best validation loss:", best_validation_loss)
print(
    "Current main learning rate:",
    optimizer.param_groups[0]["lr"],
)

Completed epoch: 4
Next epoch: 5
Best validation loss: 1.697843568013067
Current main learning rate: 0.0001

In [27]:
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

print("Completed epoch:", checkpoint["completed_epoch"])

Completed epoch: 4

In [28]:
#redoing epoch 5 after scheduler step
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print(
    "Current main learning rate:",
    optimizer.param_groups[0]["lr"],
)

Completed epoch: 4
Next epoch: 5
Current main learning rate: 0.0001

In [29]:
#restoring epoch 5 (didnt finish last time)
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 5
Training images: 5336
Main learning rate: 0.0001
Backbone learning rate: 1e-05
Start time: 2026-07-22 20:32:56.066685
Epoch 5 | Batch 1/5336 | Loss: 1.9522 | Average: 1.9522 | Elapsed: 0.00 hours
Epoch 5 | Batch 100/5336 | Loss: 1.2809 | Average: 1.6251 | Elapsed: 0.04 hours
Epoch 5 | Batch 200/5336 | Loss: 2.0752 | Average: 1.6173 | Elapsed: 0.09 hours
Epoch 5 | Batch 300/5336 | Loss: 1.2431 | Average: 1.6379 | Elapsed: 0.13 hours
Epoch 5 | Batch 400/5336 | Loss: 1.2244 | Average: 1.6690 | Elapsed: 0.17 hours
Epoch 5 | Batch 500/5336 | Loss: 0.5340 | Average: 1.6584 | Elapsed: 1.46 hours
Epoch 5 | Batch 600/5336 | Loss: 1.4680 | Average: 1.6415 | Elapsed: 1.52 hours
Epoch 5 | Batch 700/5336 | Loss: 1.7133 | Average: 1.6407 | Elapsed: 1.57 hours
Epoch 5 | Batch 800/5336 | Loss: 2.6347 | Average: 1.6432 | Elapsed: 1.59 hours
Epoch 5 | Batch 900/5336 | Loss: 2.3923 | Average: 1.6590 | Elapsed: 1.62 hours
Epoch 5 | Batch 1000/5336 | Loss: 1.7493 | Average: 1.6656 | Elapsed: 1.67 hours
Epoch 5 | Batch 1100/5336 | Loss: 0.6619 | Average: 1.6679 | Elapsed: 1.71 hours
Epoch 5 | Batch 1200/5336 | Loss: 1.5538 | Average: 1.6646 | Elapsed: 12.81 hours
Epoch 5 | Batch 1300/5336 | Loss: 2.5733 | Average: 1.6540 | Elapsed: 12.84 hours
Epoch 5 | Batch 1400/5336 | Loss: 2.0891 | Average: 1.6542 | Elapsed: 12.89 hours
Epoch 5 | Batch 1500/5336 | Loss: 2.8792 | Average: 1.6574 | Elapsed: 12.94 hours
Epoch 5 | Batch 1600/5336 | Loss: 1.2152 | Average: 1.6528 | Elapsed: 13.00 hours
Epoch 5 | Batch 1700/5336 | Loss: 1.9038 | Average: 1.6493 | Elapsed: 13.06 hours
Epoch 5 | Batch 1800/5336 | Loss: 2.5568 | Average: 1.6459 | Elapsed: 13.12 hours
Epoch 5 | Batch 1900/5336 | Loss: 2.6123 | Average: 1.6521 | Elapsed: 13.17 hours
Epoch 5 | Batch 2000/5336 | Loss: 1.3183 | Average: 1.6513 | Elapsed: 13.23 hours
Epoch 5 | Batch 2100/5336 | Loss: 1.0532 | Average: 1.6507 | Elapsed: 13.28 hours
Epoch 5 | Batch 2200/5336 | Loss: 2.6556 | Average: 1.6532 | Elapsed: 13.31 hours
Epoch 5 | Batch 2300/5336 | Loss: 1.8002 | Average: 1.6481 | Elapsed: 13.34 hours
Epoch 5 | Batch 2400/5336 | Loss: 1.6522 | Average: 1.6503 | Elapsed: 13.38 hours
Epoch 5 | Batch 2500/5336 | Loss: 1.5520 | Average: 1.6436 | Elapsed: 13.42 hours
Epoch 5 | Batch 2600/5336 | Loss: 2.2576 | Average: 1.6411 | Elapsed: 13.46 hours
Epoch 5 | Batch 2700/5336 | Loss: 2.0215 | Average: 1.6383 | Elapsed: 13.75 hours
Epoch 5 | Batch 2800/5336 | Loss: 0.8700 | Average: 1.6393 | Elapsed: 13.78 hours
Epoch 5 | Batch 2900/5336 | Loss: 1.6617 | Average: 1.6426 | Elapsed: 13.82 hours
Epoch 5 | Batch 3000/5336 | Loss: 1.4916 | Average: 1.6442 | Elapsed: 13.86 hours
Epoch 5 | Batch 3100/5336 | Loss: 1.3179 | Average: 1.6451 | Elapsed: 13.89 hours
Epoch 5 | Batch 3200/5336 | Loss: 3.0676 | Average: 1.6454 | Elapsed: 13.94 hours
Epoch 5 | Batch 3300/5336 | Loss: 2.0897 | Average: 1.6461 | Elapsed: 14.00 hours
Epoch 5 | Batch 3400/5336 | Loss: 2.2761 | Average: 1.6434 | Elapsed: 14.06 hours
Epoch 5 | Batch 3500/5336 | Loss: 1.6444 | Average: 1.6429 | Elapsed: 14.11 hours
Epoch 5 | Batch 3600/5336 | Loss: 1.4176 | Average: 1.6411 | Elapsed: 14.14 hours
Epoch 5 | Batch 3700/5336 | Loss: 3.1974 | Average: 1.6400 | Elapsed: 14.16 hours
Epoch 5 | Batch 3800/5336 | Loss: 0.7288 | Average: 1.6406 | Elapsed: 14.18 hours
Epoch 5 | Batch 3900/5336 | Loss: 1.8968 | Average: 1.6431 | Elapsed: 14.20 hours
Epoch 5 | Batch 4000/5336 | Loss: 0.8886 | Average: 1.6436 | Elapsed: 14.23 hours
Epoch 5 | Batch 4100/5336 | Loss: 4.0902 | Average: 1.6488 | Elapsed: 14.25 hours
Epoch 5 | Batch 4200/5336 | Loss: 2.4125 | Average: 1.6506 | Elapsed: 14.27 hours
Epoch 5 | Batch 4300/5336 | Loss: 1.5137 | Average: 1.6505 | Elapsed: 14.29 hours
Epoch 5 | Batch 4400/5336 | Loss: 1.3882 | Average: 1.6552 | Elapsed: 14.31 hours
Epoch 5 | Batch 4500/5336 | Loss: 2.2323 | Average: 1.6555 | Elapsed: 14.33 hours
Epoch 5 | Batch 4600/5336 | Loss: 0.6124 | Average: 1.6573 | Elapsed: 14.36 hours
Epoch 5 | Batch 4700/5336 | Loss: 2.0954 | Average: 1.6603 | Elapsed: 14.38 hours
Epoch 5 | Batch 4800/5336 | Loss: 1.1943 | Average: 1.6612 | Elapsed: 14.40 hours
Epoch 5 | Batch 4900/5336 | Loss: 1.4049 | Average: 1.6615 | Elapsed: 14.42 hours
Epoch 5 | Batch 5000/5336 | Loss: 2.1178 | Average: 1.6604 | Elapsed: 14.44 hours
Epoch 5 | Batch 5100/5336 | Loss: 1.8731 | Average: 1.6619 | Elapsed: 14.46 hours
Epoch 5 | Batch 5200/5336 | Loss: 1.7432 | Average: 1.6624 | Elapsed: 14.48 hours
Epoch 5 | Batch 5300/5336 | Loss: 1.2962 | Average: 1.6606 | Elapsed: 14.50 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_05.pth

Epoch completed successfully.
Training loss: 1.6614
Validation loss: 1.6347
Training time: 14.51 hours
Validation time: 0.07 hours
Cumulative training time: 20.19 hours
Finish time: 2026-07-23 11:07:43.123727

In [30]:
#latest checkpoint after epoch 5
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print(
    "Current main learning rate:",
    optimizer.param_groups[0]["lr"],
)
print(
    "Current backbone learning rate:",
    optimizer.param_groups[1]["lr"],
)

Completed epoch: 5
Next epoch: 6
Current main learning rate: 1e-05
Current backbone learning rate: 1.0000000000000002e-06

In [31]:
#starting epoch 6
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 6
Training images: 5336
Main learning rate: 1e-05
Backbone learning rate: 1.0000000000000002e-06
Start time: 2026-07-23 11:16:09.701885
Epoch 6 | Batch 1/5336 | Loss: 1.1957 | Average: 1.1957 | Elapsed: 0.00 hours
Epoch 6 | Batch 100/5336 | Loss: 2.0740 | Average: 1.6537 | Elapsed: 0.03 hours
Epoch 6 | Batch 200/5336 | Loss: 3.0102 | Average: 1.6054 | Elapsed: 0.06 hours
Epoch 6 | Batch 300/5336 | Loss: 0.9002 | Average: 1.5812 | Elapsed: 0.08 hours
Epoch 6 | Batch 400/5336 | Loss: 2.0233 | Average: 1.5471 | Elapsed: 0.10 hours
Epoch 6 | Batch 500/5336 | Loss: 3.3671 | Average: 1.5343 | Elapsed: 0.12 hours
Epoch 6 | Batch 600/5336 | Loss: 1.4019 | Average: 1.5193 | Elapsed: 0.14 hours
Epoch 6 | Batch 700/5336 | Loss: 0.4578 | Average: 1.5003 | Elapsed: 0.16 hours
Epoch 6 | Batch 800/5336 | Loss: 0.9191 | Average: 1.4945 | Elapsed: 0.19 hours
Epoch 6 | Batch 900/5336 | Loss: 1.5022 | Average: 1.4878 | Elapsed: 0.21 hours
Epoch 6 | Batch 1000/5336 | Loss: 2.9411 | Average: 1.4778 | Elapsed: 0.23 hours
Epoch 6 | Batch 1100/5336 | Loss: 1.2189 | Average: 1.4685 | Elapsed: 0.25 hours
Epoch 6 | Batch 1200/5336 | Loss: 2.1785 | Average: 1.4715 | Elapsed: 0.27 hours
Epoch 6 | Batch 1300/5336 | Loss: 1.5131 | Average: 1.4715 | Elapsed: 0.29 hours
Epoch 6 | Batch 1400/5336 | Loss: 1.7667 | Average: 1.4661 | Elapsed: 0.31 hours
Epoch 6 | Batch 1500/5336 | Loss: 2.7005 | Average: 1.4656 | Elapsed: 0.34 hours
Epoch 6 | Batch 1600/5336 | Loss: 0.1365 | Average: 1.4638 | Elapsed: 0.36 hours
Epoch 6 | Batch 1700/5336 | Loss: 2.3233 | Average: 1.4547 | Elapsed: 0.38 hours
Epoch 6 | Batch 1800/5336 | Loss: 0.8090 | Average: 1.4451 | Elapsed: 0.40 hours
Epoch 6 | Batch 1900/5336 | Loss: 0.7216 | Average: 1.4418 | Elapsed: 0.42 hours
Epoch 6 | Batch 2000/5336 | Loss: 1.1366 | Average: 1.4417 | Elapsed: 0.44 hours
Epoch 6 | Batch 2100/5336 | Loss: 1.3215 | Average: 1.4401 | Elapsed: 0.46 hours
Epoch 6 | Batch 2200/5336 | Loss: 1.3040 | Average: 1.4317 | Elapsed: 0.48 hours
Epoch 6 | Batch 2300/5336 | Loss: 1.7375 | Average: 1.4274 | Elapsed: 0.51 hours
Epoch 6 | Batch 2400/5336 | Loss: 1.0963 | Average: 1.4166 | Elapsed: 0.53 hours
Epoch 6 | Batch 2500/5336 | Loss: 1.8542 | Average: 1.4137 | Elapsed: 0.55 hours
Epoch 6 | Batch 2600/5336 | Loss: 1.9127 | Average: 1.4118 | Elapsed: 0.57 hours
Epoch 6 | Batch 2700/5336 | Loss: 1.0015 | Average: 1.4101 | Elapsed: 0.59 hours
Epoch 6 | Batch 2800/5336 | Loss: 0.5311 | Average: 1.4051 | Elapsed: 0.61 hours
Epoch 6 | Batch 2900/5336 | Loss: 2.5702 | Average: 1.4004 | Elapsed: 0.63 hours
Epoch 6 | Batch 3000/5336 | Loss: 1.6986 | Average: 1.4001 | Elapsed: 0.65 hours
Epoch 6 | Batch 3100/5336 | Loss: 1.1139 | Average: 1.3995 | Elapsed: 0.67 hours
Epoch 6 | Batch 3200/5336 | Loss: 1.7368 | Average: 1.3935 | Elapsed: 0.70 hours
Epoch 6 | Batch 3300/5336 | Loss: 2.2410 | Average: 1.3915 | Elapsed: 0.72 hours
Epoch 6 | Batch 3400/5336 | Loss: 1.6883 | Average: 1.3895 | Elapsed: 0.74 hours
Epoch 6 | Batch 3500/5336 | Loss: 0.9998 | Average: 1.3874 | Elapsed: 0.76 hours
Epoch 6 | Batch 3600/5336 | Loss: 1.7403 | Average: 1.3837 | Elapsed: 0.78 hours
Epoch 6 | Batch 3700/5336 | Loss: 0.2502 | Average: 1.3819 | Elapsed: 0.80 hours
Epoch 6 | Batch 3800/5336 | Loss: 0.0360 | Average: 1.3778 | Elapsed: 0.82 hours
Epoch 6 | Batch 3900/5336 | Loss: 1.8113 | Average: 1.3783 | Elapsed: 0.85 hours
Epoch 6 | Batch 4000/5336 | Loss: 3.0602 | Average: 1.3747 | Elapsed: 0.87 hours
Epoch 6 | Batch 4100/5336 | Loss: 1.7908 | Average: 1.3733 | Elapsed: 0.89 hours
Epoch 6 | Batch 4200/5336 | Loss: 2.0720 | Average: 1.3731 | Elapsed: 0.91 hours
Epoch 6 | Batch 4300/5336 | Loss: 1.2656 | Average: 1.3719 | Elapsed: 0.93 hours
Epoch 6 | Batch 4400/5336 | Loss: 0.8786 | Average: 1.3703 | Elapsed: 0.96 hours
Epoch 6 | Batch 4500/5336 | Loss: 1.0809 | Average: 1.3688 | Elapsed: 0.98 hours
Epoch 6 | Batch 4600/5336 | Loss: 0.9219 | Average: 1.3675 | Elapsed: 1.00 hours
Epoch 6 | Batch 4700/5336 | Loss: 1.6827 | Average: 1.3671 | Elapsed: 1.02 hours
Epoch 6 | Batch 4800/5336 | Loss: 2.0538 | Average: 1.3685 | Elapsed: 1.04 hours
Epoch 6 | Batch 4900/5336 | Loss: 0.6482 | Average: 1.3666 | Elapsed: 1.07 hours
Epoch 6 | Batch 5000/5336 | Loss: 0.6589 | Average: 1.3656 | Elapsed: 1.09 hours
Epoch 6 | Batch 5100/5336 | Loss: 2.0645 | Average: 1.3660 | Elapsed: 1.11 hours
Epoch 6 | Batch 5200/5336 | Loss: 2.1129 | Average: 1.3672 | Elapsed: 1.13 hours
Epoch 6 | Batch 5300/5336 | Loss: 3.8619 | Average: 1.3681 | Elapsed: 1.15 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_06.pth

Epoch completed successfully.
Training loss: 1.3686
Validation loss: 1.2874
Training time: 1.16 hours
Validation time: 0.07 hours
Cumulative training time: 21.35 hours
Finish time: 2026-07-23 12:29:53.922275

In [32]:
import pandas as pd

history_path = RUN_DIR / "training_history.csv"
history_df = pd.read_csv(history_path)

display(history_df)

,epoch,average_train_loss,average_validation_loss,training_seconds,training_hours,validation_seconds,main_learning_rate,backbone_learning_rate,completion_time
0,1,2.669919,2.356625,3720.928979,1.033591,251.220950,0.00010,0.000010,2026-07-22T13:15:29
1,2,2.142196,1.888244,8788.364654,2.441212,251.585416,0.00010,0.000010,2026-07-22T16:16:38
2,3,1.880384,1.697844,3940.074978,1.094465,341.408232,0.00010,0.000010,2026-07-22T17:46:37
3,4,1.740071,1.755049,3999.611199,1.111003,272.069183,0.00010,0.000010,2026-07-22T19:02:47
4,5,1.661423,1.634695,52240.026700,14.511119,248.149900,0.00010,0.000010,2026-07-23T11:07:41
5,6,1.368582,1.287403,4173.666068,1.159352,249.223950,0.00001,0.000001,2026-07-23T12:29:52

In [33]:
#loading latest checkpoint after epoch 6
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print("Best validation loss:", best_validation_loss)
print(
    "Current main learning rate:",
    optimizer.param_groups[0]["lr"],
)
print(
    "Current backbone learning rate:",
    optimizer.param_groups[1]["lr"],
)

Completed epoch: 6
Next epoch: 7
Best validation loss: 1.2874028298700375
Current main learning rate: 1e-05
Current backbone learning rate: 1.0000000000000002e-06

In [34]:
#epoch 7
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 7
Training images: 5336
Main learning rate: 1e-05
Backbone learning rate: 1.0000000000000002e-06
Start time: 2026-07-23 12:56:13.901393
Epoch 7 | Batch 1/5336 | Loss: 0.4309 | Average: 0.4309 | Elapsed: 0.00 hours
Epoch 7 | Batch 100/5336 | Loss: 0.9478 | Average: 1.1397 | Elapsed: 0.03 hours
Epoch 7 | Batch 200/5336 | Loss: 1.6721 | Average: 1.2698 | Elapsed: 0.06 hours
Epoch 7 | Batch 300/5336 | Loss: 1.6443 | Average: 1.2821 | Elapsed: 0.09 hours
Epoch 7 | Batch 400/5336 | Loss: 2.0230 | Average: 1.2996 | Elapsed: 0.14 hours
Epoch 7 | Batch 500/5336 | Loss: 0.6210 | Average: 1.2926 | Elapsed: 0.20 hours
Epoch 7 | Batch 600/5336 | Loss: 1.3958 | Average: 1.2839 | Elapsed: 0.26 hours
Epoch 7 | Batch 700/5336 | Loss: 1.1783 | Average: 1.2830 | Elapsed: 0.32 hours
Epoch 7 | Batch 800/5336 | Loss: 0.8173 | Average: 1.2983 | Elapsed: 0.38 hours
Epoch 7 | Batch 900/5336 | Loss: 1.1696 | Average: 1.2925 | Elapsed: 0.42 hours
Epoch 7 | Batch 1000/5336 | Loss: 1.3702 | Average: 1.2966 | Elapsed: 0.46 hours
Epoch 7 | Batch 1100/5336 | Loss: 0.5407 | Average: 1.2931 | Elapsed: 0.50 hours
Epoch 7 | Batch 1200/5336 | Loss: 1.4463 | Average: 1.2872 | Elapsed: 0.52 hours
Epoch 7 | Batch 1300/5336 | Loss: 0.6724 | Average: 1.2888 | Elapsed: 0.56 hours
Epoch 7 | Batch 1400/5336 | Loss: 1.8073 | Average: 1.2918 | Elapsed: 0.60 hours
Epoch 7 | Batch 1500/5336 | Loss: 0.8974 | Average: 1.2931 | Elapsed: 0.64 hours
Epoch 7 | Batch 1600/5336 | Loss: 2.0561 | Average: 1.2875 | Elapsed: 0.68 hours
Epoch 7 | Batch 1700/5336 | Loss: 1.1918 | Average: 1.2829 | Elapsed: 0.73 hours
Epoch 7 | Batch 1800/5336 | Loss: 1.6284 | Average: 1.2807 | Elapsed: 0.77 hours
Epoch 7 | Batch 1900/5336 | Loss: 1.6194 | Average: 1.2848 | Elapsed: 0.81 hours
Epoch 7 | Batch 2000/5336 | Loss: 0.9890 | Average: 1.2852 | Elapsed: 0.85 hours
Epoch 7 | Batch 2100/5336 | Loss: 1.5399 | Average: 1.2852 | Elapsed: 0.89 hours
Epoch 7 | Batch 2200/5336 | Loss: 0.5283 | Average: 1.2872 | Elapsed: 0.93 hours
Epoch 7 | Batch 2300/5336 | Loss: 1.5500 | Average: 1.2918 | Elapsed: 0.98 hours
Epoch 7 | Batch 2400/5336 | Loss: 1.3343 | Average: 1.2895 | Elapsed: 1.02 hours
Epoch 7 | Batch 2500/5336 | Loss: 1.9423 | Average: 1.2896 | Elapsed: 1.06 hours
Epoch 7 | Batch 2600/5336 | Loss: 2.0404 | Average: 1.2892 | Elapsed: 1.10 hours
Epoch 7 | Batch 2700/5336 | Loss: 0.5890 | Average: 1.2901 | Elapsed: 1.13 hours
Epoch 7 | Batch 2800/5336 | Loss: 0.0015 | Average: 1.2917 | Elapsed: 1.17 hours
Epoch 7 | Batch 2900/5336 | Loss: 0.8476 | Average: 1.2896 | Elapsed: 1.20 hours
Epoch 7 | Batch 3000/5336 | Loss: 1.1473 | Average: 1.2887 | Elapsed: 1.23 hours
Epoch 7 | Batch 3100/5336 | Loss: 1.5561 | Average: 1.2894 | Elapsed: 1.27 hours
Epoch 7 | Batch 3200/5336 | Loss: 1.8821 | Average: 1.2890 | Elapsed: 1.30 hours
Epoch 7 | Batch 3300/5336 | Loss: 2.1527 | Average: 1.2902 | Elapsed: 1.34 hours
Epoch 7 | Batch 3400/5336 | Loss: 0.0161 | Average: 1.2891 | Elapsed: 1.38 hours
Epoch 7 | Batch 3500/5336 | Loss: 0.8375 | Average: 1.2887 | Elapsed: 1.41 hours
Epoch 7 | Batch 3600/5336 | Loss: 1.2250 | Average: 1.2867 | Elapsed: 1.45 hours
Epoch 7 | Batch 3700/5336 | Loss: 0.5129 | Average: 1.2847 | Elapsed: 1.48 hours
Epoch 7 | Batch 3800/5336 | Loss: 0.8180 | Average: 1.2845 | Elapsed: 1.51 hours
Epoch 7 | Batch 3900/5336 | Loss: 2.6230 | Average: 1.2845 | Elapsed: 1.54 hours
Epoch 7 | Batch 4000/5336 | Loss: 1.0275 | Average: 1.2834 | Elapsed: 1.57 hours
Epoch 7 | Batch 4100/5336 | Loss: 0.5280 | Average: 1.2825 | Elapsed: 1.79 hours
Epoch 7 | Batch 4200/5336 | Loss: 1.2147 | Average: 1.2795 | Elapsed: 1.83 hours
Epoch 7 | Batch 4300/5336 | Loss: 0.9027 | Average: 1.2796 | Elapsed: 1.87 hours
Epoch 7 | Batch 4400/5336 | Loss: 1.5730 | Average: 1.2784 | Elapsed: 1.91 hours
Epoch 7 | Batch 4500/5336 | Loss: 1.0079 | Average: 1.2771 | Elapsed: 1.95 hours
Epoch 7 | Batch 4600/5336 | Loss: 1.2084 | Average: 1.2765 | Elapsed: 2.00 hours
Epoch 7 | Batch 4700/5336 | Loss: 1.1585 | Average: 1.2769 | Elapsed: 2.05 hours
Epoch 7 | Batch 4800/5336 | Loss: 1.7439 | Average: 1.2738 | Elapsed: 2.09 hours
Epoch 7 | Batch 4900/5336 | Loss: 1.1902 | Average: 1.2727 | Elapsed: 2.13 hours
Epoch 7 | Batch 5000/5336 | Loss: 0.7980 | Average: 1.2707 | Elapsed: 2.18 hours
Epoch 7 | Batch 5100/5336 | Loss: 0.7132 | Average: 1.2696 | Elapsed: 2.23 hours
Epoch 7 | Batch 5200/5336 | Loss: 1.3309 | Average: 1.2684 | Elapsed: 2.26 hours
Epoch 7 | Batch 5300/5336 | Loss: 1.1463 | Average: 1.2700 | Elapsed: 2.30 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_07.pth

Epoch completed successfully.
Training loss: 1.2693
Validation loss: 1.2327
Training time: 2.31 hours
Validation time: 0.10 hours
Cumulative training time: 23.66 hours
Finish time: 2026-07-23 15:21:01.168813

In [35]:
history_df = pd.read_csv(
    RUN_DIR / "training_history.csv"
)

display(
    history_df[
        [
            "epoch",
            "average_train_loss",
            "average_validation_loss",
            "training_hours",
            "main_learning_rate",
        ]
    ]
)

,epoch,average_train_loss,average_validation_loss,training_hours,main_learning_rate
0,1,2.669919,2.356625,1.033591,0.00010
1,2,2.142196,1.888244,2.441212,0.00010
2,3,1.880384,1.697844,1.094465,0.00010
3,4,1.740071,1.755049,1.111003,0.00010
4,5,1.661423,1.634695,14.511119,0.00010
5,6,1.368582,1.287403,1.159352,0.00001
6,7,1.269332,1.232705,2.309147,0.00001

In [36]:
#reloading latest checkpoint after epoch 7
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print("Best validation loss:", best_validation_loss)

Completed epoch: 7
Next epoch: 8
Best validation loss: 1.232704552378009

In [37]:
#epoch 8
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 8
Training images: 5336
Main learning rate: 1e-05
Backbone learning rate: 1.0000000000000002e-06
Start time: 2026-07-23 15:26:29.534704
Epoch 8 | Batch 1/5336 | Loss: 0.8703 | Average: 0.8703 | Elapsed: 0.00 hours
Epoch 8 | Batch 100/5336 | Loss: 0.8844 | Average: 1.1880 | Elapsed: 0.04 hours
Epoch 8 | Batch 200/5336 | Loss: 2.0416 | Average: 1.1862 | Elapsed: 0.07 hours
Epoch 8 | Batch 300/5336 | Loss: 0.5755 | Average: 1.2435 | Elapsed: 0.11 hours
Epoch 8 | Batch 400/5336 | Loss: 1.6868 | Average: 1.2365 | Elapsed: 0.16 hours
Epoch 8 | Batch 500/5336 | Loss: 2.2168 | Average: 1.2516 | Elapsed: 0.20 hours
Epoch 8 | Batch 600/5336 | Loss: 1.5636 | Average: 1.2475 | Elapsed: 0.26 hours
Epoch 8 | Batch 700/5336 | Loss: 2.2944 | Average: 1.2467 | Elapsed: 0.31 hours
Epoch 8 | Batch 800/5336 | Loss: 2.2687 | Average: 1.2505 | Elapsed: 0.36 hours
Epoch 8 | Batch 900/5336 | Loss: 1.3878 | Average: 1.2477 | Elapsed: 0.41 hours
Epoch 8 | Batch 1000/5336 | Loss: 1.1010 | Average: 1.2450 | Elapsed: 0.45 hours
Epoch 8 | Batch 1100/5336 | Loss: 0.9535 | Average: 1.2404 | Elapsed: 0.48 hours
Epoch 8 | Batch 1200/5336 | Loss: 1.0044 | Average: 1.2546 | Elapsed: 0.51 hours
Epoch 8 | Batch 1300/5336 | Loss: 2.2018 | Average: 1.2546 | Elapsed: 0.55 hours
Epoch 8 | Batch 1400/5336 | Loss: 1.2777 | Average: 1.2436 | Elapsed: 0.58 hours
Epoch 8 | Batch 1500/5336 | Loss: 1.8115 | Average: 1.2461 | Elapsed: 0.62 hours
Epoch 8 | Batch 1600/5336 | Loss: 0.9245 | Average: 1.2474 | Elapsed: 0.65 hours
Epoch 8 | Batch 1700/5336 | Loss: 1.1396 | Average: 1.2399 | Elapsed: 0.67 hours
Epoch 8 | Batch 1800/5336 | Loss: 0.5128 | Average: 1.2387 | Elapsed: 0.69 hours
Epoch 8 | Batch 1900/5336 | Loss: 1.1338 | Average: 1.2385 | Elapsed: 0.72 hours
Epoch 8 | Batch 2000/5336 | Loss: 1.1120 | Average: 1.2403 | Elapsed: 0.77 hours
Epoch 8 | Batch 2100/5336 | Loss: 1.6280 | Average: 1.2389 | Elapsed: 0.81 hours
Epoch 8 | Batch 2200/5336 | Loss: 0.9064 | Average: 1.2330 | Elapsed: 0.86 hours
Epoch 8 | Batch 2300/5336 | Loss: 1.7410 | Average: 1.2300 | Elapsed: 0.91 hours
Epoch 8 | Batch 2400/5336 | Loss: 0.9143 | Average: 1.2308 | Elapsed: 0.95 hours
Epoch 8 | Batch 2500/5336 | Loss: 0.6179 | Average: 1.2304 | Elapsed: 1.00 hours
Epoch 8 | Batch 2600/5336 | Loss: 1.7015 | Average: 1.2297 | Elapsed: 1.05 hours
Epoch 8 | Batch 2700/5336 | Loss: 1.8319 | Average: 1.2297 | Elapsed: 1.09 hours
Epoch 8 | Batch 2800/5336 | Loss: 1.1466 | Average: 1.2319 | Elapsed: 1.14 hours
Epoch 8 | Batch 2900/5336 | Loss: 1.8963 | Average: 1.2291 | Elapsed: 1.19 hours
Epoch 8 | Batch 3000/5336 | Loss: 1.4539 | Average: 1.2274 | Elapsed: 1.23 hours
Epoch 8 | Batch 3100/5336 | Loss: 1.1549 | Average: 1.2259 | Elapsed: 1.28 hours
Epoch 8 | Batch 3200/5336 | Loss: 1.8680 | Average: 1.2273 | Elapsed: 1.33 hours
Epoch 8 | Batch 3300/5336 | Loss: 1.1687 | Average: 1.2281 | Elapsed: 1.37 hours
Epoch 8 | Batch 3400/5336 | Loss: 0.8232 | Average: 1.2264 | Elapsed: 1.42 hours
Epoch 8 | Batch 3500/5336 | Loss: 0.4666 | Average: 1.2272 | Elapsed: 1.44 hours
Epoch 8 | Batch 3600/5336 | Loss: 0.5358 | Average: 1.2262 | Elapsed: 1.46 hours
Epoch 8 | Batch 3700/5336 | Loss: 0.7537 | Average: 1.2215 | Elapsed: 1.48 hours
Epoch 8 | Batch 3800/5336 | Loss: 0.0186 | Average: 1.2193 | Elapsed: 1.51 hours
Epoch 8 | Batch 3900/5336 | Loss: 1.9441 | Average: 1.2208 | Elapsed: 1.53 hours
Epoch 8 | Batch 4000/5336 | Loss: 0.9955 | Average: 1.2218 | Elapsed: 1.55 hours
Epoch 8 | Batch 4100/5336 | Loss: 2.0078 | Average: 1.2207 | Elapsed: 1.57 hours
Epoch 8 | Batch 4200/5336 | Loss: 1.3445 | Average: 1.2190 | Elapsed: 1.59 hours
Epoch 8 | Batch 4300/5336 | Loss: 0.9776 | Average: 1.2189 | Elapsed: 1.61 hours
Epoch 8 | Batch 4400/5336 | Loss: 0.9319 | Average: 1.2191 | Elapsed: 1.64 hours
Epoch 8 | Batch 4500/5336 | Loss: 1.2951 | Average: 1.2169 | Elapsed: 1.66 hours
Epoch 8 | Batch 4600/5336 | Loss: 0.8893 | Average: 1.2156 | Elapsed: 1.68 hours
Epoch 8 | Batch 4700/5336 | Loss: 0.7705 | Average: 1.2166 | Elapsed: 1.70 hours
Epoch 8 | Batch 4800/5336 | Loss: 1.6202 | Average: 1.2155 | Elapsed: 1.72 hours
Epoch 8 | Batch 4900/5336 | Loss: 0.9926 | Average: 1.2154 | Elapsed: 1.75 hours
Epoch 8 | Batch 5000/5336 | Loss: 1.4985 | Average: 1.2176 | Elapsed: 1.77 hours
Epoch 8 | Batch 5100/5336 | Loss: 1.1275 | Average: 1.2176 | Elapsed: 1.79 hours
Epoch 8 | Batch 5200/5336 | Loss: 1.2428 | Average: 1.2161 | Elapsed: 1.81 hours
Epoch 8 | Batch 5300/5336 | Loss: 0.7668 | Average: 1.2165 | Elapsed: 1.83 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_08.pth

Epoch completed successfully.
Training loss: 1.2177
Validation loss: 1.2019
Training time: 1.84 hours
Validation time: 0.07 hours
Cumulative training time: 25.50 hours
Finish time: 2026-07-23 17:21:10.526999

In [38]:
#checking validation loss after epoch 8
history_df = pd.read_csv(
    RUN_DIR / "training_history.csv"
)

display(
    history_df[
        [
            "epoch",
            "average_train_loss",
            "average_validation_loss",
            "training_hours",
            "main_learning_rate",
        ]
    ]
)

,epoch,average_train_loss,average_validation_loss,training_hours,main_learning_rate
0,1,2.669919,2.356625,1.033591,0.00010
1,2,2.142196,1.888244,2.441212,0.00010
2,3,1.880384,1.697844,1.094465,0.00010
3,4,1.740071,1.755049,1.111003,0.00010
4,5,1.661423,1.634695,14.511119,0.00010
5,6,1.368582,1.287403,1.159352,0.00001
6,7,1.269332,1.232705,2.309147,0.00001
7,8,1.217745,1.201944,1.841752,0.00001

In [39]:
#checkpoint 
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print("Best validation loss:", best_validation_loss)

Completed epoch: 8
Next epoch: 9
Best validation loss: 1.2019440689584378

In [41]:
#run epoch 9
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 9
Training images: 5336
Main learning rate: 1e-05
Backbone learning rate: 1.0000000000000002e-06
Start time: 2026-07-23 17:33:29.229277
Epoch 9 | Batch 1/5336 | Loss: 0.8521 | Average: 0.8521 | Elapsed: 0.00 hours
Epoch 9 | Batch 100/5336 | Loss: 0.9787 | Average: 1.1494 | Elapsed: 0.03 hours
Epoch 9 | Batch 200/5336 | Loss: 1.2988 | Average: 1.2047 | Elapsed: 0.06 hours
Epoch 9 | Batch 300/5336 | Loss: 2.1992 | Average: 1.1527 | Elapsed: 0.10 hours
Epoch 9 | Batch 400/5336 | Loss: 1.6895 | Average: 1.1497 | Elapsed: 0.14 hours
Epoch 9 | Batch 500/5336 | Loss: 1.0909 | Average: 1.1543 | Elapsed: 0.18 hours
Epoch 9 | Batch 600/5336 | Loss: 0.8409 | Average: 1.1595 | Elapsed: 0.23 hours
Epoch 9 | Batch 700/5336 | Loss: 1.4754 | Average: 1.1660 | Elapsed: 0.27 hours
Epoch 9 | Batch 800/5336 | Loss: 0.5008 | Average: 1.1557 | Elapsed: 0.32 hours
Epoch 9 | Batch 900/5336 | Loss: 1.0146 | Average: 1.1646 | Elapsed: 0.36 hours
Epoch 9 | Batch 1000/5336 | Loss: 1.8461 | Average: 1.1636 | Elapsed: 0.41 hours
Epoch 9 | Batch 1100/5336 | Loss: 0.2454 | Average: 1.1628 | Elapsed: 0.46 hours
Epoch 9 | Batch 1200/5336 | Loss: 1.2617 | Average: 1.1614 | Elapsed: 0.51 hours
Epoch 9 | Batch 1300/5336 | Loss: 0.9924 | Average: 1.1516 | Elapsed: 0.57 hours
Epoch 9 | Batch 1400/5336 | Loss: 1.1299 | Average: 1.1537 | Elapsed: 0.63 hours
Epoch 9 | Batch 1500/5336 | Loss: 1.0557 | Average: 1.1556 | Elapsed: 0.69 hours
Epoch 9 | Batch 1600/5336 | Loss: 1.5866 | Average: 1.1636 | Elapsed: 0.76 hours
Epoch 9 | Batch 1700/5336 | Loss: 0.9002 | Average: 1.1664 | Elapsed: 0.82 hours
Epoch 9 | Batch 1800/5336 | Loss: 1.8375 | Average: 1.1637 | Elapsed: 0.88 hours
Epoch 9 | Batch 1900/5336 | Loss: 2.4321 | Average: 1.1654 | Elapsed: 0.94 hours
Epoch 9 | Batch 2000/5336 | Loss: 1.9414 | Average: 1.1658 | Elapsed: 0.98 hours
Epoch 9 | Batch 2100/5336 | Loss: 0.5788 | Average: 1.1620 | Elapsed: 1.02 hours
Epoch 9 | Batch 2200/5336 | Loss: 0.8934 | Average: 1.1598 | Elapsed: 1.05 hours
Epoch 9 | Batch 2300/5336 | Loss: 1.2072 | Average: 1.1581 | Elapsed: 1.08 hours
Epoch 9 | Batch 2400/5336 | Loss: 1.3190 | Average: 1.1634 | Elapsed: 1.11 hours
Epoch 9 | Batch 2500/5336 | Loss: 0.6824 | Average: 1.1665 | Elapsed: 1.13 hours
Epoch 9 | Batch 2600/5336 | Loss: 0.8195 | Average: 1.1686 | Elapsed: 1.15 hours
Epoch 9 | Batch 2700/5336 | Loss: 0.8831 | Average: 1.1686 | Elapsed: 1.17 hours
Epoch 9 | Batch 2800/5336 | Loss: 0.5364 | Average: 1.1659 | Elapsed: 1.20 hours
Epoch 9 | Batch 2900/5336 | Loss: 1.0984 | Average: 1.1679 | Elapsed: 1.22 hours
Epoch 9 | Batch 3000/5336 | Loss: 1.0632 | Average: 1.1699 | Elapsed: 1.24 hours
Epoch 9 | Batch 3100/5336 | Loss: 1.1268 | Average: 1.1683 | Elapsed: 1.27 hours
Epoch 9 | Batch 3200/5336 | Loss: 0.8215 | Average: 1.1727 | Elapsed: 1.29 hours
Epoch 9 | Batch 3300/5336 | Loss: 3.1027 | Average: 1.1774 | Elapsed: 1.31 hours
Epoch 9 | Batch 3400/5336 | Loss: 0.6636 | Average: 1.1771 | Elapsed: 1.34 hours
Epoch 9 | Batch 3500/5336 | Loss: 1.7058 | Average: 1.1745 | Elapsed: 1.36 hours
Epoch 9 | Batch 3600/5336 | Loss: 1.5156 | Average: 1.1719 | Elapsed: 1.38 hours
Epoch 9 | Batch 3700/5336 | Loss: 0.6369 | Average: 1.1710 | Elapsed: 1.40 hours
Epoch 9 | Batch 3800/5336 | Loss: 0.7025 | Average: 1.1701 | Elapsed: 1.43 hours
Epoch 9 | Batch 3900/5336 | Loss: 0.7589 | Average: 1.1695 | Elapsed: 1.45 hours
Epoch 9 | Batch 4000/5336 | Loss: 1.0190 | Average: 1.1725 | Elapsed: 1.47 hours
Epoch 9 | Batch 4100/5336 | Loss: 0.4192 | Average: 1.1699 | Elapsed: 1.50 hours
Epoch 9 | Batch 4200/5336 | Loss: 0.5764 | Average: 1.1719 | Elapsed: 1.52 hours
Epoch 9 | Batch 4300/5336 | Loss: 0.9197 | Average: 1.1708 | Elapsed: 1.54 hours
Epoch 9 | Batch 4400/5336 | Loss: 1.3620 | Average: 1.1725 | Elapsed: 1.57 hours
Epoch 9 | Batch 4500/5336 | Loss: 1.0285 | Average: 1.1730 | Elapsed: 1.59 hours
Epoch 9 | Batch 4600/5336 | Loss: 0.4845 | Average: 1.1746 | Elapsed: 1.61 hours
Epoch 9 | Batch 4700/5336 | Loss: 0.9703 | Average: 1.1730 | Elapsed: 1.64 hours
Epoch 9 | Batch 4800/5336 | Loss: 0.5776 | Average: 1.1732 | Elapsed: 1.66 hours
Epoch 9 | Batch 4900/5336 | Loss: 0.0121 | Average: 1.1739 | Elapsed: 1.68 hours
Epoch 9 | Batch 5000/5336 | Loss: 1.2145 | Average: 1.1745 | Elapsed: 1.70 hours
Epoch 9 | Batch 5100/5336 | Loss: 0.2335 | Average: 1.1761 | Elapsed: 1.73 hours
Epoch 9 | Batch 5200/5336 | Loss: 2.8576 | Average: 1.1759 | Elapsed: 1.75 hours
Epoch 9 | Batch 5300/5336 | Loss: 1.2106 | Average: 1.1770 | Elapsed: 1.77 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_09.pth

Epoch completed successfully.
Training loss: 1.1760
Validation loss: 1.1788
Training time: 1.78 hours
Validation time: 0.07 hours
Cumulative training time: 27.28 hours
Finish time: 2026-07-23 19:24:52.769426

In [42]:
history_df = pd.read_csv(
    RUN_DIR / "training_history.csv"
)

display(
    history_df[
        [
            "epoch",
            "average_train_loss",
            "average_validation_loss",
            "training_hours",
            "main_learning_rate",
        ]
    ]
)

,epoch,average_train_loss,average_validation_loss,training_hours,main_learning_rate
0,1,2.669919,2.356625,1.033591,0.00010
1,2,2.142196,1.888244,2.441212,0.00010
2,3,1.880384,1.697844,1.094465,0.00010
3,4,1.740071,1.755049,1.111003,0.00010
4,5,1.661423,1.634695,14.511119,0.00010
5,6,1.368582,1.287403,1.159352,0.00001
6,7,1.269332,1.232705,2.309147,0.00001
7,8,1.217745,1.201944,1.841752,0.00001
8,9,1.175973,1.178760,1.783136,0.00001

In [43]:
#checkpoint
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print("Best validation loss:", best_validation_loss)
print(
    "Current main learning rate:",
    optimizer.param_groups[0]["lr"],
)

Completed epoch: 9
Next epoch: 10
Best validation loss: 1.178760255537283
Current main learning rate: 1e-05

In [44]:
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 10
Training images: 5336
Main learning rate: 1e-05
Backbone learning rate: 1.0000000000000002e-06
Start time: 2026-07-23 20:53:24.910445
Epoch 10 | Batch 1/5336 | Loss: 0.7182 | Average: 0.7182 | Elapsed: 0.00 hours
Epoch 10 | Batch 100/5336 | Loss: 1.3853 | Average: 1.1300 | Elapsed: 0.04 hours
Epoch 10 | Batch 200/5336 | Loss: 1.2820 | Average: 1.1367 | Elapsed: 0.08 hours
Epoch 10 | Batch 300/5336 | Loss: 0.5195 | Average: 1.1179 | Elapsed: 0.13 hours
Epoch 10 | Batch 400/5336 | Loss: 1.3569 | Average: 1.1369 | Elapsed: 0.17 hours
Epoch 10 | Batch 500/5336 | Loss: 0.8331 | Average: 1.1388 | Elapsed: 0.21 hours
Epoch 10 | Batch 600/5336 | Loss: 1.2950 | Average: 1.1421 | Elapsed: 0.25 hours
Epoch 10 | Batch 700/5336 | Loss: 2.0845 | Average: 1.1385 | Elapsed: 0.30 hours
Epoch 10 | Batch 800/5336 | Loss: 2.8576 | Average: 1.1395 | Elapsed: 0.34 hours
Epoch 10 | Batch 900/5336 | Loss: 1.7603 | Average: 1.1383 | Elapsed: 0.38 hours
Epoch 10 | Batch 1000/5336 | Loss: 0.4434 | Average: 1.1346 | Elapsed: 0.42 hours
Epoch 10 | Batch 1100/5336 | Loss: 0.8820 | Average: 1.1403 | Elapsed: 0.45 hours
Epoch 10 | Batch 1200/5336 | Loss: 1.0380 | Average: 1.1431 | Elapsed: 0.48 hours
Epoch 10 | Batch 1300/5336 | Loss: 0.9162 | Average: 1.1435 | Elapsed: 0.53 hours
Epoch 10 | Batch 1400/5336 | Loss: 0.7683 | Average: 1.1448 | Elapsed: 0.57 hours
Epoch 10 | Batch 1500/5336 | Loss: 0.5932 | Average: 1.1485 | Elapsed: 0.77 hours
Epoch 10 | Batch 1600/5336 | Loss: 1.1074 | Average: 1.1474 | Elapsed: 0.81 hours
Epoch 10 | Batch 1700/5336 | Loss: 1.9225 | Average: 1.1465 | Elapsed: 0.87 hours
Epoch 10 | Batch 1800/5336 | Loss: 1.0623 | Average: 1.1393 | Elapsed: 0.93 hours
Epoch 10 | Batch 1900/5336 | Loss: 0.4232 | Average: 1.1427 | Elapsed: 0.99 hours
Epoch 10 | Batch 2000/5336 | Loss: 1.1931 | Average: 1.1463 | Elapsed: 1.02 hours
Epoch 10 | Batch 2100/5336 | Loss: 0.6143 | Average: 1.1491 | Elapsed: 1.05 hours
Epoch 10 | Batch 2200/5336 | Loss: 1.3866 | Average: 1.1519 | Elapsed: 1.09 hours
Epoch 10 | Batch 2300/5336 | Loss: 0.8481 | Average: 1.1483 | Elapsed: 1.13 hours
Epoch 10 | Batch 2400/5336 | Loss: 0.7968 | Average: 1.1459 | Elapsed: 1.48 hours
Epoch 10 | Batch 2500/5336 | Loss: 0.6089 | Average: 1.1450 | Elapsed: 1.51 hours
Epoch 10 | Batch 2600/5336 | Loss: 1.0784 | Average: 1.1457 | Elapsed: 1.55 hours
Epoch 10 | Batch 2700/5336 | Loss: 0.8429 | Average: 1.1451 | Elapsed: 1.59 hours
Epoch 10 | Batch 2800/5336 | Loss: 0.9757 | Average: 1.1488 | Elapsed: 1.63 hours
Epoch 10 | Batch 2900/5336 | Loss: 0.7559 | Average: 1.1495 | Elapsed: 15.51 hours
Epoch 10 | Batch 3000/5336 | Loss: 1.0988 | Average: 1.1518 | Elapsed: 15.54 hours
Epoch 10 | Batch 3100/5336 | Loss: 1.1752 | Average: 1.1548 | Elapsed: 15.56 hours
Epoch 10 | Batch 3200/5336 | Loss: 1.9007 | Average: 1.1535 | Elapsed: 15.58 hours
Epoch 10 | Batch 3300/5336 | Loss: 1.8579 | Average: 1.1537 | Elapsed: 15.61 hours
Epoch 10 | Batch 3400/5336 | Loss: 0.8799 | Average: 1.1515 | Elapsed: 15.63 hours
Epoch 10 | Batch 3500/5336 | Loss: 1.7886 | Average: 1.1557 | Elapsed: 15.65 hours
Epoch 10 | Batch 3600/5336 | Loss: 1.4507 | Average: 1.1558 | Elapsed: 15.67 hours
Epoch 10 | Batch 3700/5336 | Loss: 0.7878 | Average: 1.1591 | Elapsed: 15.69 hours
Epoch 10 | Batch 3800/5336 | Loss: 1.6288 | Average: 1.1573 | Elapsed: 15.72 hours
Epoch 10 | Batch 3900/5336 | Loss: 1.3663 | Average: 1.1588 | Elapsed: 15.74 hours
Epoch 10 | Batch 4000/5336 | Loss: 0.9909 | Average: 1.1587 | Elapsed: 15.77 hours
Epoch 10 | Batch 4100/5336 | Loss: 1.2896 | Average: 1.1582 | Elapsed: 15.79 hours
Epoch 10 | Batch 4200/5336 | Loss: 0.8505 | Average: 1.1569 | Elapsed: 15.82 hours
Epoch 10 | Batch 4300/5336 | Loss: 0.3955 | Average: 1.1553 | Elapsed: 15.85 hours
Epoch 10 | Batch 4400/5336 | Loss: 1.3937 | Average: 1.1552 | Elapsed: 15.87 hours
Epoch 10 | Batch 4500/5336 | Loss: 0.5015 | Average: 1.1544 | Elapsed: 15.90 hours
Epoch 10 | Batch 4600/5336 | Loss: 1.8108 | Average: 1.1528 | Elapsed: 15.93 hours
Epoch 10 | Batch 4700/5336 | Loss: 0.5009 | Average: 1.1516 | Elapsed: 15.96 hours
Epoch 10 | Batch 4800/5336 | Loss: 0.7632 | Average: 1.1517 | Elapsed: 16.00 hours
Epoch 10 | Batch 4900/5336 | Loss: 0.9512 | Average: 1.1519 | Elapsed: 16.05 hours
Epoch 10 | Batch 5000/5336 | Loss: 0.7502 | Average: 1.1521 | Elapsed: 16.11 hours
Epoch 10 | Batch 5100/5336 | Loss: 0.5993 | Average: 1.1495 | Elapsed: 16.14 hours
Epoch 10 | Batch 5200/5336 | Loss: 1.5579 | Average: 1.1500 | Elapsed: 16.17 hours
Epoch 10 | Batch 5300/5336 | Loss: 0.0674 | Average: 1.1483 | Elapsed: 16.22 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_10.pth

Epoch completed successfully.
Training loss: 1.1487
Validation loss: 1.1579
Training time: 16.23 hours
Validation time: 0.18 hours
Cumulative training time: 43.52 hours
Finish time: 2026-07-24 13:18:17.773414

In [45]:
history_df = pd.read_csv(
    RUN_DIR / "training_history.csv"
)

display(
    history_df[
        [
            "epoch",
            "average_train_loss",
            "average_validation_loss",
            "training_hours",
            "main_learning_rate",
        ]
    ]
)

,epoch,average_train_loss,average_validation_loss,training_hours,main_learning_rate
0,1,2.669919,2.356625,1.033591,0.00010
1,2,2.142196,1.888244,2.441212,0.00010
2,3,1.880384,1.697844,1.094465,0.00010
3,4,1.740071,1.755049,1.111003,0.00010
4,5,1.661423,1.634695,14.511119,0.00010
5,6,1.368582,1.287403,1.159352,0.00001
6,7,1.269332,1.232705,2.309147,0.00001
7,8,1.217745,1.201944,1.841752,0.00001
8,9,1.175973,1.178760,1.783136,0.00001
9,10,1.148679,1.157855,16.230681,0.00001

In [46]:
#loading latest checkpoint
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print("Best validation loss:", best_validation_loss)
print(
    "Current main learning rate:",
    optimizer.param_groups[0]["lr"],
)
print(
    "Current backbone learning rate:",
    optimizer.param_groups[1]["lr"],
)

Completed epoch: 10
Next epoch: 11
Best validation loss: 1.157855187086741
Current main learning rate: 1.0000000000000002e-06
Current backbone learning rate: 1.0000000000000002e-07

In [47]:
#epoch 11
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 11
Training images: 5336
Main learning rate: 1.0000000000000002e-06
Backbone learning rate: 1.0000000000000002e-07
Start time: 2026-07-24 13:24:52.185984
Epoch 11 | Batch 1/5336 | Loss: 1.0218 | Average: 1.0218 | Elapsed: 0.00 hours
Epoch 11 | Batch 100/5336 | Loss: 1.2771 | Average: 1.1469 | Elapsed: 0.03 hours
Epoch 11 | Batch 200/5336 | Loss: 1.7571 | Average: 1.1479 | Elapsed: 0.06 hours
Epoch 11 | Batch 300/5336 | Loss: 0.7494 | Average: 1.1486 | Elapsed: 0.11 hours
Epoch 11 | Batch 400/5336 | Loss: 1.6522 | Average: 1.1305 | Elapsed: 0.16 hours
Epoch 11 | Batch 500/5336 | Loss: 0.8874 | Average: 1.1428 | Elapsed: 0.21 hours
Epoch 11 | Batch 600/5336 | Loss: 0.7718 | Average: 1.1313 | Elapsed: 0.26 hours
Epoch 11 | Batch 700/5336 | Loss: 0.7197 | Average: 1.1303 | Elapsed: 0.31 hours
Epoch 11 | Batch 800/5336 | Loss: 0.5704 | Average: 1.1204 | Elapsed: 0.36 hours
Epoch 11 | Batch 900/5336 | Loss: 0.8236 | Average: 1.1160 | Elapsed: 0.41 hours
Epoch 11 | Batch 1000/5336 | Loss: 0.5876 | Average: 1.1083 | Elapsed: 0.46 hours
Epoch 11 | Batch 1100/5336 | Loss: 1.5522 | Average: 1.1077 | Elapsed: 0.52 hours
Epoch 11 | Batch 1200/5336 | Loss: 0.5339 | Average: 1.1017 | Elapsed: 0.57 hours
Epoch 11 | Batch 1300/5336 | Loss: 2.6938 | Average: 1.1182 | Elapsed: 0.62 hours
Epoch 11 | Batch 1400/5336 | Loss: 1.9183 | Average: 1.1128 | Elapsed: 0.66 hours
Epoch 11 | Batch 1500/5336 | Loss: 1.5295 | Average: 1.1095 | Elapsed: 0.71 hours
Epoch 11 | Batch 1600/5336 | Loss: 0.8564 | Average: 1.1115 | Elapsed: 0.76 hours
Epoch 11 | Batch 1700/5336 | Loss: 2.8235 | Average: 1.1155 | Elapsed: 0.80 hours
Epoch 11 | Batch 1800/5336 | Loss: 2.1180 | Average: 1.1183 | Elapsed: 0.85 hours
Epoch 11 | Batch 1900/5336 | Loss: 0.4481 | Average: 1.1150 | Elapsed: 0.90 hours
Epoch 11 | Batch 2000/5336 | Loss: 0.7905 | Average: 1.1157 | Elapsed: 0.94 hours
Epoch 11 | Batch 2100/5336 | Loss: 1.2132 | Average: 1.1201 | Elapsed: 1.00 hours
Epoch 11 | Batch 2200/5336 | Loss: 1.0664 | Average: 1.1176 | Elapsed: 1.07 hours
Epoch 11 | Batch 2300/5336 | Loss: 0.5662 | Average: 1.1173 | Elapsed: 1.14 hours
Epoch 11 | Batch 2400/5336 | Loss: 0.9984 | Average: 1.1182 | Elapsed: 1.21 hours
Epoch 11 | Batch 2500/5336 | Loss: 0.3581 | Average: 1.1178 | Elapsed: 1.27 hours
Epoch 11 | Batch 2600/5336 | Loss: 0.9266 | Average: 1.1146 | Elapsed: 1.34 hours
Epoch 11 | Batch 2700/5336 | Loss: 0.7244 | Average: 1.1154 | Elapsed: 1.39 hours
Epoch 11 | Batch 2800/5336 | Loss: 0.6489 | Average: 1.1152 | Elapsed: 1.44 hours
Epoch 11 | Batch 2900/5336 | Loss: 0.8503 | Average: 1.1157 | Elapsed: 1.49 hours
Epoch 11 | Batch 3000/5336 | Loss: 1.6442 | Average: 1.1143 | Elapsed: 1.53 hours
Epoch 11 | Batch 3100/5336 | Loss: 1.1411 | Average: 1.1136 | Elapsed: 1.56 hours
Epoch 11 | Batch 3200/5336 | Loss: 0.7128 | Average: 1.1134 | Elapsed: 1.60 hours
Epoch 11 | Batch 3300/5336 | Loss: 0.4178 | Average: 1.1110 | Elapsed: 1.64 hours
Epoch 11 | Batch 3400/5336 | Loss: 2.4920 | Average: 1.1117 | Elapsed: 1.67 hours
Epoch 11 | Batch 3500/5336 | Loss: 0.8608 | Average: 1.1113 | Elapsed: 1.71 hours
Epoch 11 | Batch 3600/5336 | Loss: 0.7632 | Average: 1.1124 | Elapsed: 1.74 hours
Epoch 11 | Batch 3700/5336 | Loss: 1.3268 | Average: 1.1112 | Elapsed: 1.78 hours
Epoch 11 | Batch 3800/5336 | Loss: 1.3922 | Average: 1.1110 | Elapsed: 1.80 hours
Epoch 11 | Batch 3900/5336 | Loss: 1.2556 | Average: 1.1133 | Elapsed: 1.82 hours
Epoch 11 | Batch 4000/5336 | Loss: 0.4715 | Average: 1.1123 | Elapsed: 1.84 hours
Epoch 11 | Batch 4100/5336 | Loss: 2.5063 | Average: 1.1149 | Elapsed: 1.87 hours
Epoch 11 | Batch 4200/5336 | Loss: 1.2366 | Average: 1.1153 | Elapsed: 1.89 hours
Epoch 11 | Batch 4300/5336 | Loss: 0.4855 | Average: 1.1156 | Elapsed: 1.91 hours
Epoch 11 | Batch 4400/5336 | Loss: 1.6979 | Average: 1.1144 | Elapsed: 1.94 hours
Epoch 11 | Batch 4500/5336 | Loss: 0.7931 | Average: 1.1116 | Elapsed: 1.97 hours
Epoch 11 | Batch 4600/5336 | Loss: 1.5444 | Average: 1.1095 | Elapsed: 1.99 hours
Epoch 11 | Batch 4700/5336 | Loss: 2.1516 | Average: 1.1104 | Elapsed: 2.01 hours
Epoch 11 | Batch 4800/5336 | Loss: 0.4555 | Average: 1.1111 | Elapsed: 2.04 hours
Epoch 11 | Batch 4900/5336 | Loss: 1.5546 | Average: 1.1103 | Elapsed: 2.06 hours
Epoch 11 | Batch 5000/5336 | Loss: 1.9422 | Average: 1.1116 | Elapsed: 2.08 hours
Epoch 11 | Batch 5100/5336 | Loss: 1.7445 | Average: 1.1114 | Elapsed: 2.11 hours
Epoch 11 | Batch 5200/5336 | Loss: 1.0005 | Average: 1.1096 | Elapsed: 2.13 hours
Epoch 11 | Batch 5300/5336 | Loss: 0.5473 | Average: 1.1104 | Elapsed: 2.15 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_11.pth

Epoch completed successfully.
Training loss: 1.1099
Validation loss: 1.1463
Training time: 2.16 hours
Validation time: 0.07 hours
Cumulative training time: 45.67 hours
Finish time: 2026-07-24 15:38:45.644979

In [48]:
#epoch 11 validation loss check
history_df = pd.read_csv(
    RUN_DIR / "training_history.csv"
)

display(
    history_df[
        [
            "epoch",
            "average_train_loss",
            "average_validation_loss",
            "training_hours",
            "main_learning_rate",
        ]
    ]
)

,epoch,average_train_loss,average_validation_loss,training_hours,main_learning_rate
0,1,2.669919,2.356625,1.033591,0.000100
1,2,2.142196,1.888244,2.441212,0.000100
2,3,1.880384,1.697844,1.094465,0.000100
3,4,1.740071,1.755049,1.111003,0.000100
4,5,1.661423,1.634695,14.511119,0.000100
5,6,1.368582,1.287403,1.159352,0.000010
6,7,1.269332,1.232705,2.309147,0.000010
7,8,1.217745,1.201944,1.841752,0.000010
8,9,1.175973,1.178760,1.783136,0.000010
9,10,1.148679,1.157855,16.230681,0.000010
10,11,1.109908,1.146273,2.159384,0.000001

In [49]:
#checkpoint
checkpoint = torch.load(
    LATEST_CHECKPOINT,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

optimizer.load_state_dict(
    checkpoint["optimizer_state_dict"]
)

scheduler.load_state_dict(
    checkpoint["scheduler_state_dict"]
)

completed_epoch = checkpoint["completed_epoch"]
epoch_number = completed_epoch + 1

cumulative_training_seconds = checkpoint[
    "cumulative_training_seconds"
]

best_validation_loss = checkpoint[
    "best_validation_loss"
]

print("Completed epoch:", completed_epoch)
print("Next epoch:", epoch_number)
print("Best validation loss:", best_validation_loss)
print(
    "Current main learning rate:",
    optimizer.param_groups[0]["lr"],
)

Completed epoch: 11
Next epoch: 12
Best validation loss: 1.1462732903545463
Current main learning rate: 1.0000000000000002e-06

In [50]:
#epoch 12
(
    cumulative_training_seconds,
    best_validation_loss,
) = run_and_save_detr_epoch(
    epoch_number=epoch_number,
    cumulative_training_seconds=
        cumulative_training_seconds,
    best_validation_loss=
        best_validation_loss,
)

Beginning full DETR training
Epoch: 12
Training images: 5336
Main learning rate: 1.0000000000000002e-06
Backbone learning rate: 1.0000000000000002e-07
Start time: 2026-07-24 15:41:58.711047
Epoch 12 | Batch 1/5336 | Loss: 2.0698 | Average: 2.0698 | Elapsed: 0.00 hours
Epoch 12 | Batch 100/5336 | Loss: 0.4486 | Average: 1.1094 | Elapsed: 0.02 hours
Epoch 12 | Batch 200/5336 | Loss: 0.7446 | Average: 1.1045 | Elapsed: 0.04 hours
Epoch 12 | Batch 300/5336 | Loss: 0.8471 | Average: 1.0845 | Elapsed: 0.07 hours
Epoch 12 | Batch 400/5336 | Loss: 1.2383 | Average: 1.1159 | Elapsed: 0.09 hours
Epoch 12 | Batch 500/5336 | Loss: 2.3643 | Average: 1.0977 | Elapsed: 0.11 hours
Epoch 12 | Batch 600/5336 | Loss: 0.5184 | Average: 1.1076 | Elapsed: 0.14 hours
Epoch 12 | Batch 700/5336 | Loss: 0.8958 | Average: 1.1125 | Elapsed: 0.16 hours
Epoch 12 | Batch 800/5336 | Loss: 0.5239 | Average: 1.1225 | Elapsed: 0.18 hours
Epoch 12 | Batch 900/5336 | Loss: 0.6820 | Average: 1.1169 | Elapsed: 0.21 hours
Epoch 12 | Batch 1000/5336 | Loss: 2.3761 | Average: 1.1168 | Elapsed: 0.23 hours
Epoch 12 | Batch 1100/5336 | Loss: 0.1102 | Average: 1.1076 | Elapsed: 0.26 hours
Epoch 12 | Batch 1200/5336 | Loss: 2.4299 | Average: 1.1115 | Elapsed: 0.28 hours
Epoch 12 | Batch 1300/5336 | Loss: 1.0466 | Average: 1.1103 | Elapsed: 0.31 hours
Epoch 12 | Batch 1400/5336 | Loss: 0.6205 | Average: 1.1082 | Elapsed: 0.33 hours
Epoch 12 | Batch 1500/5336 | Loss: 0.8897 | Average: 1.1035 | Elapsed: 0.36 hours
Epoch 12 | Batch 1600/5336 | Loss: 0.8424 | Average: 1.1029 | Elapsed: 0.39 hours
Epoch 12 | Batch 1700/5336 | Loss: 1.1938 | Average: 1.1021 | Elapsed: 0.42 hours
Epoch 12 | Batch 1800/5336 | Loss: 0.7302 | Average: 1.1056 | Elapsed: 0.44 hours
Epoch 12 | Batch 1900/5336 | Loss: 0.5450 | Average: 1.1010 | Elapsed: 0.47 hours
Epoch 12 | Batch 2000/5336 | Loss: 1.4672 | Average: 1.0990 | Elapsed: 0.50 hours
Epoch 12 | Batch 2100/5336 | Loss: 1.3014 | Average: 1.0968 | Elapsed: 0.53 hours
Epoch 12 | Batch 2200/5336 | Loss: 0.4218 | Average: 1.0934 | Elapsed: 0.56 hours
Epoch 12 | Batch 2300/5336 | Loss: 1.1588 | Average: 1.0868 | Elapsed: 0.59 hours
Epoch 12 | Batch 2400/5336 | Loss: 1.0152 | Average: 1.0844 | Elapsed: 0.62 hours
Epoch 12 | Batch 2500/5336 | Loss: 2.1202 | Average: 1.0855 | Elapsed: 0.65 hours
Epoch 12 | Batch 2600/5336 | Loss: 0.9441 | Average: 1.0874 | Elapsed: 0.67 hours
Epoch 12 | Batch 2700/5336 | Loss: 0.9933 | Average: 1.0937 | Elapsed: 0.70 hours
Epoch 12 | Batch 2800/5336 | Loss: 2.5969 | Average: 1.0944 | Elapsed: 0.72 hours
Epoch 12 | Batch 2900/5336 | Loss: 0.0004 | Average: 1.0953 | Elapsed: 0.75 hours
Epoch 12 | Batch 3000/5336 | Loss: 1.1260 | Average: 1.0956 | Elapsed: 0.78 hours
Epoch 12 | Batch 3100/5336 | Loss: 1.1013 | Average: 1.0977 | Elapsed: 0.81 hours
Epoch 12 | Batch 3200/5336 | Loss: 0.7276 | Average: 1.1013 | Elapsed: 0.83 hours
Epoch 12 | Batch 3300/5336 | Loss: 1.0377 | Average: 1.1027 | Elapsed: 0.86 hours
Epoch 12 | Batch 3400/5336 | Loss: 0.8988 | Average: 1.1055 | Elapsed: 0.89 hours
Epoch 12 | Batch 3500/5336 | Loss: 0.7055 | Average: 1.1041 | Elapsed: 0.91 hours
Epoch 12 | Batch 3600/5336 | Loss: 0.3592 | Average: 1.1035 | Elapsed: 0.94 hours
Epoch 12 | Batch 3700/5336 | Loss: 1.3863 | Average: 1.1008 | Elapsed: 0.96 hours
Epoch 12 | Batch 3800/5336 | Loss: 0.6724 | Average: 1.0996 | Elapsed: 0.98 hours
Epoch 12 | Batch 3900/5336 | Loss: 1.1706 | Average: 1.1007 | Elapsed: 1.01 hours
Epoch 12 | Batch 4000/5336 | Loss: 0.4985 | Average: 1.1002 | Elapsed: 1.03 hours
Epoch 12 | Batch 4100/5336 | Loss: 1.1090 | Average: 1.1011 | Elapsed: 1.06 hours
Epoch 12 | Batch 4200/5336 | Loss: 1.7015 | Average: 1.1015 | Elapsed: 1.08 hours
Epoch 12 | Batch 4300/5336 | Loss: 0.8041 | Average: 1.1023 | Elapsed: 1.11 hours
Epoch 12 | Batch 4400/5336 | Loss: 0.9374 | Average: 1.1043 | Elapsed: 1.13 hours
Epoch 12 | Batch 4500/5336 | Loss: 1.3336 | Average: 1.1049 | Elapsed: 1.16 hours
Epoch 12 | Batch 4600/5336 | Loss: 0.0085 | Average: 1.1049 | Elapsed: 1.18 hours
Epoch 12 | Batch 4700/5336 | Loss: 1.2130 | Average: 1.1052 | Elapsed: 1.21 hours
Epoch 12 | Batch 4800/5336 | Loss: 0.7783 | Average: 1.1033 | Elapsed: 1.24 hours
Epoch 12 | Batch 4900/5336 | Loss: 1.1219 | Average: 1.1053 | Elapsed: 1.28 hours
Epoch 12 | Batch 5000/5336 | Loss: 0.7449 | Average: 1.1030 | Elapsed: 1.33 hours
Epoch 12 | Batch 5100/5336 | Loss: 0.8968 | Average: 1.1033 | Elapsed: 1.37 hours
Epoch 12 | Batch 5200/5336 | Loss: 0.7115 | Average: 1.1039 | Elapsed: 1.42 hours
Epoch 12 | Batch 5300/5336 | Loss: 0.7571 | Average: 1.1058 | Elapsed: 1.46 hours
Validation batch 1/1335
Validation batch 100/1335
Validation batch 200/1335
Validation batch 300/1335
Validation batch 400/1335
Validation batch 500/1335
Validation batch 600/1335
Validation batch 700/1335
Validation batch 800/1335
Validation batch 900/1335
Validation batch 1000/1335
Validation batch 1100/1335
Validation batch 1200/1335
Validation batch 1300/1335
New best validation checkpoint saved.
Latest checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\latest_checkpoint.pth
Epoch checkpoint: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\checkpoint_epoch_12.pth

Epoch completed successfully.
Training loss: 1.1059
Validation loss: 1.1431
Training time: 1.48 hours
Validation time: 0.13 hours
Cumulative training time: 47.15 hours
Finish time: 2026-07-24 17:18:38.429216

In [51]:
history_df = pd.read_csv(
    RUN_DIR / "training_history.csv"
)

display(
    history_df[
        [
            "epoch",
            "average_train_loss",
            "average_validation_loss",
            "training_hours",
            "main_learning_rate",
        ]
    ]
)

,epoch,average_train_loss,average_validation_loss,training_hours,main_learning_rate
0,1,2.669919,2.356625,1.033591,0.000100
1,2,2.142196,1.888244,2.441212,0.000100
2,3,1.880384,1.697844,1.094465,0.000100
3,4,1.740071,1.755049,1.111003,0.000100
4,5,1.661423,1.634695,14.511119,0.000100
5,6,1.368582,1.287403,1.159352,0.000010
6,7,1.269332,1.232705,2.309147,0.000010
7,8,1.217745,1.201944,1.841752,0.000010
8,9,1.175973,1.178760,1.783136,0.000010
9,10,1.148679,1.157855,16.230681,0.000010
10,11,1.109908,1.146273,2.159384,0.000001
11,12,1.105888,1.143148,1.478847,0.000001

In [52]:
#best checkpoint
best_checkpoint_path = RUN_DIR / "best_checkpoint.pth"

checkpoint = torch.load(
    best_checkpoint_path,
    map_location=device,
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

model.to(device)
model.eval()

print("Loaded best epoch:", checkpoint["completed_epoch"])
print("Best validation loss:", checkpoint["best_validation_loss"])

Loaded best epoch: 12
Best validation loss: 1.1431484567980936

In [53]:
%pip install torchmetrics pycocotools

Requirement already satisfied: torchmetrics in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (1.9.0)
Requirement already satisfied: pycocotools in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (2.0.11)
Requirement already satisfied: numpy>1.20.0 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from torchmetrics) (2.5.1)
Requirement already satisfied: packaging>17.1 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from torchmetrics) (26.2)
Requirement already satisfied: torch>=2.0.0 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from torchmetrics) (2.13.0)
Requirement already satisfied: lightning-utilities>=0.15.3 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from torchmetrics) (0.15.3)
Requirement already satisfied: typing_extensions in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from lightning-utilities>=0.15.3->torchmetrics) (4.16.0)
Requirement already satisfied: filelock in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from torch>=2.0.0->torchmetrics) (3.30.3)
Requirement already satisfied: setuptools>=77.0.3 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from torch>=2.0.0->torchmetrics) (83.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from torch>=2.0.0->torchmetrics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from torch>=2.0.0->torchmetrics) (3.6.1)
Requirement already satisfied: jinja2 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from torch>=2.0.0->torchmetrics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from torch>=2.0.0->torchmetrics) (2026.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from sympy>=1.13.3->torch>=2.0.0->torchmetrics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\megdo\Desktop\underwater-object-detection\venv\Lib\site-packages (from jinja2->torch>=2.0.0->torchmetrics) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

In [54]:
from torchmetrics.detection.mean_ap import MeanAveragePrecision

test_metric = MeanAveragePrecision(
    box_format="xyxy",
    iou_type="bbox",
    class_metrics=True,
)

In [56]:
#evaluation cell
import time
import torch

model.eval()
test_metric.reset()

total_inference_seconds = 0.0
total_images = 0

with torch.no_grad():
    for batch in test_loader:

        pixel_values = batch["pixel_values"].to(device)
        pixel_mask = batch["pixel_mask"].to(device)
        labels = batch["labels"]

        start_time = time.perf_counter()

        outputs = model(
            pixel_values=pixel_values,
            pixel_mask=pixel_mask,
        )

        total_inference_seconds += (
            time.perf_counter() - start_time
        )

        target_sizes = torch.stack(
            [
                label["orig_size"]
                for label in labels
            ]
        ).to(device)

        predictions = (
            processor.post_process_object_detection(
                outputs,
                target_sizes=target_sizes,
                threshold=0.0,
            )
        )

        metric_predictions = []
        metric_targets = []

        for prediction, label in zip(
            predictions,
            labels,
        ):
            metric_predictions.append(
                {
                    "boxes": prediction["boxes"].cpu(),
                    "scores": prediction["scores"].cpu(),
                    "labels": prediction["labels"].cpu(),
                }
            )

            image_height = label["orig_size"][0]
            image_width = label["orig_size"][1]

            boxes = label["boxes"].clone()

            centre_x = boxes[:, 0]
            centre_y = boxes[:, 1]
            box_width = boxes[:, 2]
            box_height = boxes[:, 3]

            x_min = (
                centre_x - box_width / 2
            ) * image_width

            y_min = (
                centre_y - box_height / 2
            ) * image_height

            x_max = (
                centre_x + box_width / 2
            ) * image_width

            y_max = (
                centre_y + box_height / 2
            ) * image_height

            target_boxes = torch.stack(
                [x_min, y_min, x_max, y_max],
                dim=1,
            )

            metric_targets.append(
                {
                    "boxes": target_boxes.cpu(),
                    "labels": label[
                        "class_labels"
                    ].cpu(),
                }
            )

        test_metric.update(
            metric_predictions,
            metric_targets,
        )

        total_images += len(labels)

test_results = test_metric.compute()

average_inference_seconds = (
    total_inference_seconds / total_images
)

fps = 1 / average_inference_seconds

print("Test evaluation complete")
print("Images evaluated:", total_images)
print("mAP@0.5:0.95:", float(test_results["map"]))
print("mAP@0.5:", float(test_results["map_50"]))
print(
    "Average inference time:",
    average_inference_seconds,
    "seconds/image",
)
print("Approximate FPS:", fps)

Test evaluation complete
Images evaluated: 1111
mAP@0.5:0.95: 0.23586353659629822
mAP@0.5: 0.46585574746131897
Average inference time: 0.14626225436644497 seconds/image
Approximate FPS: 6.837033958840832

In [57]:
class_names = [
    "holothurian",
    "echinus",
    "scallop",
    "starfish",
]

print("Per-class AP@0.5:0.95")

for class_name, ap_value in zip(
    class_names,
    test_results["map_per_class"],
):
    print(
        class_name,
        float(ap_value),
    )

Per-class AP@0.5:0.95
holothurian 0.2180209904909134
echinus 0.3618415892124176
scallop 0.05784988775849342
starfish 0.30574169754981995

In [58]:
print(
    "Classes returned:",
    test_results["classes"],
)

Classes returned: tensor([0, 1, 2, 3], dtype=torch.int32)

In [59]:
import pandas as pd

detr_summary = pd.DataFrame(
    [
        {
            "model": "DETR ResNet-50",
            "dataset": "DUO test",
            "best_epoch": 12,
            "mAP_50": float(test_results["map_50"]),
            "mAP_50_95": float(test_results["map"]),
            "average_inference_seconds": average_inference_seconds,
            "fps": fps,
            "test_images": total_images,
        }
    ]
)

detr_summary_path = (
    RUN_DIR / "detr_test_summary.csv"
)

detr_summary.to_csv(
    detr_summary_path,
    index=False,
)

display(detr_summary)

print("Saved to:", detr_summary_path)

,model,dataset,best_epoch,mAP_50,mAP_50_95,average_inference_seconds,fps,test_images
0,DETR ResNet-50,DUO test,12,0.465856,0.235864,0.146262,6.837034,1111

Saved to: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\detr_test_summary.csv

In [60]:
detr_per_class = pd.DataFrame(
    {
        "class_id": test_results["classes"].cpu().numpy(),
        "class_name": class_names,
        "AP_50_95": [
            float(value)
            for value in test_results["map_per_class"]
        ],
    }
)

detr_per_class_path = (
    RUN_DIR / "detr_per_class_results.csv"
)

detr_per_class.to_csv(
    detr_per_class_path,
    index=False,
)

display(detr_per_class)

print("Saved to:", detr_per_class_path)

   class_id   class_name  AP_50_95
0         0  holothurian  0.218021
1         1      echinus  0.361842
2         2      scallop  0.057850
3         3     starfish  0.305742

Saved to: C:\Users\megdo\Desktop\underwater-object-detection\results\detr\duo_detr_resnet50_baseline_corrected\detr_per_class_results.csv